"""Beneath Sünden materializer — the runtime consumer the entire Plan 1–6 stack deferred to.

Every prior Sünden plan (1–6) ended with an explicit honest-deferral pointing here:
Plans 1–6 are pure substrate (generator, persistence, set-piece/trope/quest attach) with
zero non-test runtime consumers until THIS module.  This module is the keystone.  Tasks
1–8 (Plan 7) implement it completely.

-----
Pipeline shape
-----

``materialize(request, ...)`` is the five-stage async coordinator::

    design → fill → curate → attach → commit

All stages run inside a parent ``dungeon.materialize`` OTEL span; each stage's child span
nests under it in order.  Only the curate stage is ``await``-ed; the other four are
synchronous calls inside the async coordinator.  The async shape is forced by the SDK
``complete_with_tools`` being a coroutine: a nested ``asyncio.run`` from the running uvicorn
event loop (or from the Task-7 async look-ahead worker) would raise ``RuntimeError``
unconditionally, so ``materialize`` is declared ``async def`` and the curate stage is
``async def _stage_curate``.

``MaterializationRequest`` is a frozen, hashable value object (``@dataclass(frozen=True,
slots=True)``) carrying the full specification for one materialisation run.
``frontier`` is accepted at ``MaterializationRequest.build`` only for validation (confirming
``frontier_edge`` is a member of the live frontier); it is NOT stored as a field so the
hash is stable regardless of how the frontier list grows between construction and use.

-----
Plan 5 binding — persistence transaction (spec §7.5)
-----

The commit stage runs ONE transaction on the **caller-owned** connection accessed via
``persistence._conn``.  This is the sanctioned Plan-5 caller-owned-boundary seam:
``DungeonStore`` deliberately exposes no public ``commit()``/``rollback()``; Plan 5 tests
drive the connection directly (``test_persistence.py`` lines 173/340); Task 6 is the
production caller doing the same.

Seed = Expansion 0: on a fresh save (``load_map`` + ``load_frontier`` both empty — loudly
detected, never assumed) the surface entrance is committed FIRST as
``Expansion(expansion_id=0, new_nodes=[entrance], new_edges=[])`` before the first
generated expansion (``expansion_id >= 1``).  The entrance belongs to no
``Expansion.new_nodes`` generated by the pipeline, so it is never persisted by a generated
``commit_expansion`` — the Seed=Expansion-0 contract is the only path.

On ``PersistError`` the connection is rolled back (``conn.rollback()``) so NO
half-attached expansion / orphan ledger rows survive.  SQLite does NOT auto-rollback on
``IntegrityError``; the explicit rollback is mandatory.

``.rolled`` (the ``RolledSetPiece`` from each ``AttachReport``) is persisted inside this
same transaction via the real Plan-5 append-only primitive
``record_mutation(kind="setpiece_state", ...)``.  It is NEVER recomputed — the save is
truth.  It is persisted EXACTLY as the attach stage produced it (spec §7 freeze target).

**Mask persistence is a documented Plan-5-API gap.**  ``commit_expansion`` persists only
``RegionNode.to_dict()`` (id / expansion_id / theme / depth_score).  There is NO mask BLOB
write path on ``commit_expansion``; fill grids are not threaded to the commit stage; and no
Plan 1–6 code consumes a persisted mask on reload.  The mask is inert until a future plan
adds a mask-BLOB column and a loader.  This is NOT papered over — it is flagged here and
in the Post-Implementation Corrections ledger (item 10).

-----
Plan 6 binding — attach_set_piece coalescence entry point
-----

The attach stage invokes ``attach_set_piece(...)`` once per (region, set_piece) INSIDE the
``dungeon.materialize.attach`` span.  ``attach_set_piece`` is the Plan 6 single coalescence
entry point — it internally rolls, starts tropes, seeds quests, opens threads, and emits
the ``setpiece.attach`` / ``trope.start`` / ``quest.seed`` nested spans.  Plan 7 does NOT
re-emit those; they nest inside the ``dungeon.materialize.attach`` span automatically via
the OTEL context.  Plan 5 emits ``ledger.add`` / ``ledger.resolve`` — also nested
automatically.  Plan 7 owns ONLY ``dungeon.materialize.*`` / ``frontier.expand`` /
``frontier.region_transition`` / ``frontier.lookahead``.

-----
Byte-pinned span contracts (consumed here)
-----

- ``GenerationReport.as_dict()`` → ``dungeon.materialize.design`` span attributes.
  The exact key-set of ``GenerationReport.as_dict()`` is byte-pinned to the design span;
  dict-valued entries are JSON-serialised (``json.dumps(v, sort_keys=True)``).

- ``DepthReport.as_dict()`` → ``dungeon.materialize.attach`` span attributes.
  ``DepthReport.as_dict()`` has **no** ``expansion_id`` / ``stage`` keys (unlike
  ``GenerationReport.as_dict()``); the attach span helper drops the pre-baked ``stage``
  injection.  The 4 scalar keys of ``DepthReport.as_dict()`` are set directly on the span
  (honored at the routed ``SPAN_ROUTES`` extract layer — the established Task-2 through
  Task-6 byte-pinned pattern from ``dungeon_materialize.py``).

-----
Contracts (No Silent Fallbacks / save-is-truth)
-----

- **Curation-failure-is-LOUD**: the one-shot SDK curation pass
  (``complete_with_tools``) failing (``LlmClientError``), returning non-JSON, or
  returning a non-dict ALWAYS raises ``CurationError`` and
  aborts the materialisation transaction.  There is NO fallback that ships the raw
  assembled manifest stamped as curated.  The curate span carries ``curated=false`` +
  ``reason`` before the raise (lie-detector visibility).

- **Save-is-truth**: the raw design + fill output is seed-reproducible (``_region_interior_seed``
  is a deterministic blake2b mixer).  Curation DELIBERATELY breaks byte-reproducibility
  (the LLM pass selects/refines; its output is not seed-deterministic).  Frozen expansions
  and ``.rolled`` set-piece state are NEVER recomputed from seed — if they are in the save
  they are final.

-----
Async pipeline + look-ahead worker
-----

``async def materialize`` is the coordinator; the frontier look-ahead worker
(``lookahead_worker.register_lookahead_worker``) is its async consumer — it ``await``s
``materialize(...)`` directly from inside a background task, which is why the event-loop
ownership must be unambiguous (no nested ``asyncio.run``).

**HONEST AS-BUILT STATUS (do not overclaim):**  ``lookahead_worker.register_lookahead_worker``
is a complete, wiring-tested implementation proven end-to-end against the REAL
``GameSnapshot._apply_world_patch_inner`` → ``notify_region_transition`` producer (non-circular
teeth test, ``tests/dungeon/test_materializer_wiring.py``).  However, it has **ZERO production
callers**: the live WebSocket session lifecycle does NOT yet construct a save-conn
``DungeonStore`` / resolve bundle / palette / pack_tropes / campaign_seed at session-open
and call ``register_lookahead_worker(...)``.  Therefore the ADR-106
"Plans 1–6 are pure substrate with zero non-test runtime consumers" bottleneck is
**REDUCED** (the consuming runtime seam now exists and is proven) but **NOT fully closed**
(no live session activates it; ``observers=0`` on live ``frontier.region_transition`` spans
is the lie-detector signal that the worker is not yet registered).  Live-session
registration is an **OPEN, TRACKED follow-up** requiring a session-integration story —
NOT closed by Plan 7.  Do not read any doc claiming Plan 7 removed the bottleneck
without checking for that story.
"""

from __future__ import annotations

import asyncio
import hashlib
import json
import logging
import time
from dataclasses import dataclass, field
from typing import Any

from opentelemetry import trace as _otel_trace

from sidequest.agents.claude_client import LlmClientError
from sidequest.agents.model_routing import CallType, resolve_model
from sidequest.agents.tooling_protocol import CacheableBlock, Message
from sidequest.dungeon.interiors import generate_interior
from sidequest.dungeon.interiors.grid import WALL, Grid
from sidequest.dungeon.persistence import DungeonStore, FrontierEdge, PersistError
from sidequest.dungeon.region_graph import (
    DepthReport,
    Expansion,
    ExpansionGenerationError,
    GenerationReport,
    JaquaysConfig,
    RegionGraph,
    assign_depth_scores,
    attach_expansion,
    generate_expansion,
)
from sidequest.dungeon.setpiece_attach import AttachReport, attach_set_piece
from sidequest.dungeon.themes import ThemePalette
from sidequest.game.cookbook.assemble import assemble_region
from sidequest.game.cookbook.loader import CookbookBundle
from sidequest.game.cookbook.models import RegionContentManifest
from sidequest.game.creature_core import EdgePool, creature_edge_pool_from_hp
from sidequest.game.session import GameSnapshot
from sidequest.telemetry.spans.dungeon_materialize import (
    dungeon_curate_degraded_span,
    dungeon_curate_parse_failed_span,
    dungeon_materialize_attach_span,
    dungeon_materialize_commit_span,
    dungeon_materialize_curate_span,
    dungeon_materialize_design_span,
    dungeon_materialize_fill_span,
    dungeon_materialize_mask_span,
    dungeon_materialize_span,
    frontier_expand_span,
)

logger = logging.getLogger(__name__)

# ADR-106 Amendment A (story 50-26) — Layer-1 wall-clock cap on the WHOLE
# curate stage (all attempts). Module-level so it is injectable (tests set
# a tiny value; the deadline path is otherwise unverifiable without a 25 s
# test). The load-bearing no-multi-minute-freeze guarantee.
CURATE_DEADLINE_S: float = 25.0

__all__ = [
    "AttachResult",
    "CuratedCreature",
    "MaterializationRequest",
    "RegionCuration",
    "RegionFill",
    "assemble_region",
    "materialize",
]

# ---------------------------------------------------------------------------
# §12-style tunable knobs (Plan 7 Task 3)
# ---------------------------------------------------------------------------
#
# The per-region interior grid size is NOT carried by RegionNode and spec §5.2
# does NOT specify interior dimensions (spec line 120: "All thresholds and
# burst knobs are tunable in the world config"; Plan 7 is server-only — no
# content edits). The materializer therefore OWNS this as a §12-style tunable
# default knob, reconciled at execution exactly like the plan's §12 ledger
# resolved its three other knobs.
#
# 49×49 is chosen deliberately: it is odd (the maze-maker carve generators in
# interiors/ work on odd coordinates with midpoint carving), generous enough
# that gen_roomcorridor (max_rooms=12, room_max=7) produces non-degenerate room
# placement rather than a sparse retry-loop dropout. A single clear default —
# NOT a per-theme framework, NOT speculative config plumbing.
DEFAULT_INTERIOR_WIDTH = 49
DEFAULT_INTERIOR_HEIGHT = 49

# gen_roomcorridor's OWN guard raises below 5×5 (loud — fine). The real SILENT
# risk is its room-placement retry loop yielding sparse/degenerate rooms at
# valid-but-small dims. We refuse roomcorridor regions below this generous
# floor (comfortably above the generator's own 5) and fail loudly rather than
# silently shrink/grow/skip (CLAUDE.md: No Silent Fallbacks). Other algorithms
# rely on generate_interior's own loud too-small guard — not re-implemented here.
ROOMCORRIDOR_MIN_DIM = 25

# generate_interior's braid sub-seed is `seed ^ 0x5EED`, which degenerates to 0
# at seed == 0x5EED (24301). We derive per-region seeds with a non-XOR blake2b
# mixer (the Plan-2/3 _subseed precedent), but additionally refuse the fixed
# point loudly if a derived seed ever lands exactly on it.
_BRAID_FIXED_POINT = 0x5EED  # == 24301

# ---------------------------------------------------------------------------
# CR → HP → Edge seam (ADR-014 / ADR-078) — Plan 7 Task 4 OWNS this
# ---------------------------------------------------------------------------
#
# `cookbook.assemble_region` ships raw `cr` (a float, B/X-via-SRD-5.1
# Challenge Rating) on every wandering-table row and the big_bad by
# contract — its docstring states explicitly "CR→Edge translation is the
# oq-1 materializer seam (ADR-014/078) — NOT done here." ADR-078 deleted
# raw HP from runtime entities: every materialized actor carries an
# `EdgePool`. So the seam is CR → HP-equivalent → the SINGLE canonical
# `creature_edge_pool_from_hp` (promoted from session.py in this task) →
# EdgePool, identical in shape to every other engine-materialized actor
# (`world_materialization._apply_npc` precedent).
#
# The CR→HP map is a Plan-7-OWNED §-style decision (there is no shipped
# CR→HP table — corpus rows are SRD-5.1 CR only, no hp column). It is
# B/X-shaped and strictly monotonic in cr: `hp = max(1, round(cr * _CR_HP))`.
# `_CR_HP = 8` reads as "≈ one d8 hit die's worth of composure per point
# of Challenge Rating" — a CR 1 creature seeds an 8-Edge pool, CR 5 → 40,
# CR 10 → 80, and a fractional CR 0.25 kobold → max(1, round(2)) = 2. This
# is not a B/X stat-block transcription (those vary per monster); it is a
# deterministic, monotone, documented composure seed so the curated deep
# has Edge that scales with depth-banded CR. Tuning the constant is a
# §11-style content-tuning lever, not a save migration (ADR-078 §"A pure
# view function. No materialized-effect state ... retune without
# migrations").
_CR_HP = 8


def _edge_from_cr(cr: float) -> EdgePool:
    """CR → HP-equivalent → canonical EdgePool (the owned seam).

    Funnels through the ONE promoted ``creature_edge_pool_from_hp`` so the
    pool shape (full, ``OnResolution`` recovery, empty thresholds) is byte
    identical to the NPC-patch path and ``placeholder_edge_pool``. Not a
    per-call ``if cr is not None`` guard — every creature crossing the
    cookbook seam is translated here, end to end.

    ``round()`` is banker's rounding; safe for all SRD CRs at
    ``_CR_HP=8`` (every ``cr*8`` is integral, so no half-integer boundary
    is ever hit) — a future tuner picking an odd ``_CR_HP`` must
    re-verify the half-integer rounding boundary.
    """
    hp = max(1, round(cr * _CR_HP))
    return creature_edge_pool_from_hp(hp)


def _region_interior_seed(campaign_seed: int, expansion_id: int, region_id: str) -> int:
    """Deterministic per-region interior seed.

    Mirrors ``region_graph.generator._subseed`` /
    ``setpiece_attach`` exactly: a pipe-delimited UTF-8 string →
    ``blake2b(digest_size=8)`` → big-endian int. blake2b, NOT XOR — the
    house mixer; we do not invent a new scheme. Identical
    ``(campaign_seed, expansion_id, region_id)`` ⇒ identical seed ⇒
    identical raw fill (the determinism contract).
    """
    digest = hashlib.blake2b(
        f"{campaign_seed}|{expansion_id}|{region_id}".encode(),
        digest_size=8,
    ).digest()
    return int.from_bytes(digest, "big")


# ---------------------------------------------------------------------------
# Story 52-2 — ADR-096 mask emit (fill-stage seam)
# ---------------------------------------------------------------------------
#
# ADR-096 §2: "Cell-stepped math is canonical. Tokens occupy one cell;
# movement is N cells per turn; reach is Chebyshev radius `speed/5`; AoE
# is evaluated cell-by-cell against the mask. The PNG is the visual; the
# mask is the truth." This emit seam turns the fill stage's raw Grid into
# the ADR-096-shaped mask + derived block so persistence (52-3), PNG
# (52-4), and UI (52-5) can consume it without re-deriving.
#
# ``ADR096_CELL_WIDTH`` is the locked ADR-096 constant (pixels per cell);
# all materialized regions share it. ``_MASK_WALL`` / ``_MASK_FLOOR`` are
# the locked wall/floor characters of the ASCII alphabet (consumed by 52-4
# PNG rendering). The mask uses ``\n`` as a row separator.
ADR096_CELL_WIDTH = 28
_MASK_WALL = b"#"
_MASK_FLOOR = b"."
_MASK_ROW_SEP = b"\n"


@dataclass(frozen=True, slots=True)
class BlockInfo:
    """ADR-096 cell-stepped block metadata for one region's mask.

    The block is the anchor for downstream cell math (token placement,
    movement validation, AoE evaluation per ADR-096 §2). ``cell_width``
    is locked to ``ADR096_CELL_WIDTH`` (28) by the ADR; ``grid_width`` /
    ``grid_height`` are the source grid's cell counts (columns / rows);
    ``origin_x`` / ``origin_y`` are the base coordinate (default 0 — the
    block is laid out from the upper-left).
    """

    cell_width: int
    grid_width: int
    grid_height: int
    origin_x: int = 0
    origin_y: int = 0


@dataclass(frozen=True, slots=True)
class RegionMask:
    """ADR-096 mask + derived block for one region.

    ``grid`` is the SAME ``Grid`` object the mask was emitted from (no
    copy that can drift). ``mask_bytes`` is the ASCII serialization
    (``#`` walls, ``.`` floors, ``\\n`` row separators). ``mask_sha`` is
    ``hashlib.sha256(mask_bytes).hexdigest()`` (the dedupe key + GM-panel
    lie-detector). ``block`` is the cell-math anchor.

    Note: ``frozen`` blocks field reassignment but ``grid`` is a mutable
    list-of-lists; treat as read-only (same caveat as ``RegionFill.grid``).
    """

    grid: Grid
    mask_bytes: bytes
    mask_sha: str
    block: BlockInfo


def _emit_mask(grid: Grid) -> RegionMask:
    """Turn a filled ``Grid`` into the ADR-096-shaped ``RegionMask``.

    The mask is the truth (ADR-096 §2). ``FLOOR`` cells become ``.``,
    ``WALL`` cells become ``#``; rows are joined with ``\\n``. SHA-256 is
    computed over the resulting bytes; the block carries the canonical
    ``cell_width=28`` plus the source grid's dimensions.

    Raises ``ValueError`` (No Silent Fallbacks) when the grid has zero
    rows OR zero columns — an empty mask is a silent lie and must not be
    emitted.
    """
    if not grid or not grid[0]:
        raise ValueError(
            "_emit_mask: cannot emit a mask from an empty grid (no rows or no "
            "cells). ADR-096 requires real wall/floor topology; an empty mask "
            "would be a silent lie. No Silent Fallbacks."
        )
    rows = bytearray()
    for y, row in enumerate(grid):
        if y > 0:
            rows.extend(_MASK_ROW_SEP)
        for cell in row:
            rows.extend(_MASK_WALL if cell == WALL else _MASK_FLOOR)
    mask_bytes = bytes(rows)
    mask_sha = hashlib.sha256(mask_bytes).hexdigest()
    block = BlockInfo(
        cell_width=ADR096_CELL_WIDTH,
        grid_width=len(grid[0]),
        grid_height=len(grid),
    )
    return RegionMask(grid=grid, mask_bytes=mask_bytes, mask_sha=mask_sha, block=block)


@dataclass(frozen=True, slots=True)
class RegionFill:
    """In-memory result of filling one region's interior (Plan 7 Task 3).

    A frozen, slotted value object — same idiom as Task 1's
    ``MaterializationRequest`` and ``FrontierEdge``. ADR-055
    ``rooms.yaml`` shape + ADR-096 mask sidecar serialization is the
    COMMIT stage's job (Task 6), not fill's: this is purely the
    intermediate per-region grid + the metadata the lie-detector span
    needs.

    Story 52-2 adds ``mask``: the ADR-096 mask + derived block, emitted
    inside the fill stage once per region. New ``RegionFill`` instances
    produced by ``_stage_fill`` always carry a non-None mask; the default
    of ``None`` preserves backward compatibility with test fixtures that
    construct ``RegionFill`` directly without going through fill.

    Note: ``frozen`` blocks field reassignment but ``grid`` is a mutable
    list-of-lists; treat it as read-only by convention.
    """

    region_id: str
    algorithm: str
    width: int
    height: int
    braid_ratio: float
    grid: Grid
    mask: RegionMask | None = None


@dataclass(frozen=True, slots=True)
class CuratedCreature:
    """One curated creature crossing the cookbook→materializer seam.

    The cookbook ships raw corpus rows (``cr``/``xp``); ADR-078 forbids
    raw HP/CR on a materialized actor. This object is what survives the
    seam: identity (``name``/``creature_type``), the curator-refined
    ``telegraph``, and an :class:`EdgePool` (``edge``) — NO ``cr``, NO
    ``hp``, NO ``xp`` (the same shape discipline as
    ``world_materialization._apply_npc`` building ``CreatureCore(...,
    edge=<EdgePool>)``; we mirror the *shape* without fabricating the
    non-blank ``description``/``personality`` ``CreatureCore`` demands —
    those are Task 6's snapshot-application concern, not curate's).
    """

    name: str
    creature_type: str
    telegraph: str
    edge: EdgePool


@dataclass(frozen=True, slots=True)
class RegionCuration:
    """In-memory curated content for one expansion (Plan 7 Task 4).

    Curation deliberately breaks byte-reproducibility (the one-shot SDK
    ``complete_with_tools`` pass): ``assemble_region`` is deterministic up
    to the seam, the post-curation output is NOT seed-reproducible — the save, not the
    seed, is truth (spec §7). This is the curate stage's OUTPUT; applying
    it to a ``GameSnapshot`` / persisting it is Task 6 (commit). Because
    every creature here already carries an :class:`EdgePool` and no raw
    cr/hp, Task 6 commits an Edge-only snapshot (no raw-cr-in-committed-
    snapshot — flagged for Task 6's snapshot-application binding).

    Note: ``frozen`` blocks field reassignment but the dict/list fields
    are mutable; treat them as read-only by convention (same
    false-immutability caveat as ``RegionFill.grid``).
    """

    region_manifests: dict[str, RegionContentManifest]
    region_creatures: dict[str, list[CuratedCreature]]
    region_big_bad: dict[str, CuratedCreature | None]
    region_look: dict[str, str]
    curated: bool = True
    raw_seed_reproducible: bool = field(default=False)
    # ADR-106 Amendment A: region ids that Layer-2-degraded (shipped the
    # deterministic assemble_region manifest instead of a curated verdict).
    # Empty on a fully-curated expansion. `curated` is the expansion-level
    # rollup — it is False whenever this is non-empty (a degraded region is
    # NEVER stamped curated=True: the forbidden silent fallback).
    uncurated_regions: frozenset[str] = field(default=frozenset())

    def creatures_for_region(self, region_id: str) -> list[CuratedCreature]:
        """Fail-loud lookup — an unknown region is a bug, not an empty list."""
        if region_id not in self.region_creatures:
            raise KeyError(
                f"no curated creatures for region {region_id!r}; "
                f"have: {sorted(self.region_creatures)}"
            )
        return self.region_creatures[region_id]

    def big_bad_for_region(self, region_id: str) -> CuratedCreature | None:
        if region_id not in self.region_big_bad:
            raise KeyError(
                f"no big_bad slot for region {region_id!r}; have: {sorted(self.region_big_bad)}"
            )
        return self.region_big_bad[region_id]


# ---------------------------------------------------------------------------
# Value object
# ---------------------------------------------------------------------------


@dataclass(frozen=True, slots=True)
class MaterializationRequest:
    """Frozen, hashable specification for one materialisation run.

    Construct via :meth:`build` — it runs the loud validation and coerces
    ``attach_region_ids`` from a ``list[str]`` to a ``tuple[str, ...]`` so the
    object stays genuinely hashable (lists are unhashable). The bare
    constructor is the dataclass-generated one (positional fields, no
    validation) and is used only internally by :meth:`build`.

    Validation rules (enforced by :meth:`build`, no silent defaults):
    - ``expansion_id >= 1`` — expansion 0 is reserved for the seed/entrance
      per the Seed = Expansion 0 contract; negative values are always invalid.
    - ``frontier_edge`` must appear (by ``frontier_edge_id``) in the supplied
      ``frontier`` list — proves the edge exists before the request is built.
    - ``burst_magnitude >= 1`` — a zero or negative burst is incoherent.

    ``frontier`` is a :meth:`build`-only validation parameter: it is never
    stored as a field and does not affect equality or hashing.
    """

    campaign_seed: int
    expansion_id: int
    frontier_edge: FrontierEdge
    attach_region_ids: tuple[str, ...]
    heading: str
    burst_magnitude: int
    lookahead_breadth: int

    @classmethod
    def build(
        cls,
        *,
        campaign_seed: int,
        expansion_id: int,
        frontier_edge: FrontierEdge,
        attach_region_ids: list[str] | tuple[str, ...],
        heading: str,
        burst_magnitude: int,
        lookahead_breadth: int,
        frontier: list[FrontierEdge],
    ) -> MaterializationRequest:
        """Validate then build a frozen request. No silent defaults.

        ``frontier`` is consumed here only to prove ``frontier_edge`` is a live
        frontier member; it is never stored on the returned object.
        """
        if expansion_id < 1:
            raise ValueError(
                f"expansion_id must be >= 1 (expansion 0 is reserved for the "
                f"seed/entrance per the Seed=Expansion-0 contract); got {expansion_id!r}"
            )
        if burst_magnitude < 1:
            raise ValueError(
                f"burst_magnitude must be >= 1 (a zero/negative burst is "
                f"incoherent); got {burst_magnitude!r}"
            )
        frontier_ids = frozenset(fe.frontier_edge_id for fe in frontier)
        if frontier_edge.frontier_edge_id not in frontier_ids:
            raise ValueError(
                f"frontier_edge {frontier_edge.frontier_edge_id!r} is not in the "
                f"supplied frontier list (known ids: {sorted(frontier_ids)}). "
                f"A frontier_edge not present in the frontier cannot be expanded."
            )
        return cls(
            campaign_seed,
            expansion_id,
            frontier_edge,
            tuple(attach_region_ids),
            heading,
            burst_magnitude,
            lookahead_breadth,
        )


# ---------------------------------------------------------------------------
# Stage seams — each raises NotImplementedError at Task 1
# ---------------------------------------------------------------------------


def _stage_design(
    request: MaterializationRequest,
    *,
    graph: RegionGraph | None,
    palette: ThemePalette | None,
    span: _otel_trace.Span,
) -> tuple[Expansion, GenerationReport]:
    """Plan 7 Task 2: design stage — depth-filtered theme_pool + expansion generation.

    Depth-filters the palette via ``palette.themes_for_depth(depth_score)``
    (depth_score = ``request.frontier_edge.spawn_depth_score`` per the Seed=Expansion-0
    contract), calls ``generate_expansion``, and sets ``report.as_dict()`` as the
    exact span attribute set (byte-pinned GM-panel contract).

    Invariants (No Silent Fallbacks):
    - ``graph`` and ``palette`` must be real objects — ``None`` is rejected loudly.
    - Empty theme_pool after filtering → loud ``ValueError`` (generation meaningless).
    - ``ExpansionGenerationError`` propagates unchanged — no retry with smaller burst,
      no swallowing.  The span carries a failure attribute before re-raise so the GM
      panel can see the failure (lie-detector visibility).
    """
    if graph is None:
        raise ValueError(
            "_stage_design requires a real RegionGraph — "
            "graph=None is not valid (No Silent Fallbacks)"
        )
    if palette is None:
        raise ValueError(
            "_stage_design requires a real ThemePalette — "
            "palette=None is not valid (No Silent Fallbacks)"
        )
    depth_score: float = request.frontier_edge.spawn_depth_score

    eligible_themes = palette.themes_for_depth(depth_score)
    if not eligible_themes:
        raise ValueError(
            f"No themes eligible at depth_score={depth_score!r} — theme_pool would be "
            f"empty, which makes expansion generation meaningless. "
            f"Check the depth_band definitions in the theme palette."
        )
    theme_pool: list[str] = [t.id for t in eligible_themes]

    try:
        expansion, report = generate_expansion(
            graph=graph,
            campaign_seed=request.campaign_seed,
            expansion_id=request.expansion_id,
            attach_region_ids=list(request.attach_region_ids),
            theme_pool=theme_pool,
            config=JaquaysConfig(connection_burst=request.burst_magnitude),
        )
    except ExpansionGenerationError as exc:
        # Lie-detector: mark the span with the failure before re-raising so the
        # GM panel sees it.  No swallowing, no retry-with-smaller-burst.
        span.set_attribute("error", str(exc))
        span.set_attribute("failing", json.dumps(exc.failing, sort_keys=True))
        raise

    # Byte-pinned span attribute contract: exactly report.as_dict() keys/values.
    # invariants_passed is a dict — serialise as JSON so OTEL can carry it.
    report_dict = report.as_dict()
    for k, v in report_dict.items():
        if isinstance(v, dict):
            span.set_attribute(k, json.dumps(v, sort_keys=True))
        else:
            span.set_attribute(k, v)

    return expansion, report


def _stage_fill(
    request: MaterializationRequest,
    *,
    expansion: Expansion | None,
    palette: ThemePalette | None,
    span: _otel_trace.Span,
) -> dict[str, RegionFill]:
    """Plan 7 Task 3: fill stage — generate each region's interior grid.

    For every region node in ``expansion``, resolves its theme's interior
    algorithm + params + braid_ratio from ``palette`` and calls
    ``interiors.generate_interior``. Returns a ``dict`` mapping
    ``region_id -> RegionFill``; iteration order = ``expansion.new_nodes``
    order (dict insertion-order is a Python 3.7+ language guarantee). The
    ADR-055 ``rooms.yaml`` shape / ADR-096 mask sidecar serialization is
    consumed at Task 6 (commit), NOT here.

    Invariants (No Silent Fallbacks):
    - ``expansion`` and ``palette`` must be real objects — ``None`` is
      rejected loudly.
    - A region whose ``theme`` id is absent from ``palette.themes`` →
      loud ``ValueError`` (no skip, no default theme).
    - A roomcorridor region below ``ROOMCORRIDOR_MIN_DIM`` → loud
      ``ValueError`` naming the region/algorithm/dims/floor (the silent
      degenerate-rooms risk; no shrink/grow/skip).
    - A derived per-region seed equal to the braid fixed point
      (``0x5EED`` == 24301) → loud ``ValueError`` (would feed the braid
      sub-seed its degenerate fixed point).
    - An unknown algorithm raises via ``generate_interior``'s OWN guard
      (not re-implemented here) — it propagates unchanged.

    Any failure sets ``error`` on the span before raising so the GM panel
    sees the fill failure (lie-detector visibility) — no swallowing.
    """
    if expansion is None:
        raise ValueError(
            "_stage_fill requires a real Expansion — "
            "expansion=None is not valid (No Silent Fallbacks)"
        )
    if palette is None:
        raise ValueError(
            "_stage_fill requires a real ThemePalette — "
            "palette=None is not valid (No Silent Fallbacks)"
        )

    fills: dict[str, RegionFill] = {}
    try:
        for node in expansion.new_nodes:
            if node.theme not in palette.themes:
                raise ValueError(
                    f"region {node.id!r} references theme {node.theme!r} which "
                    f"is absent from the palette (have: "
                    f"{sorted(palette.themes)}). No silent default theme."
                )
            theme = palette.themes[node.theme]
            algorithm = theme.interior.algorithm
            braid_ratio = theme.interior.braid_ratio
            params = theme.interior.params
            width = DEFAULT_INTERIOR_WIDTH
            height = DEFAULT_INTERIOR_HEIGHT

            # roomcorridor degenerate-rooms floor (carry-forward): loud, no
            # shrink/grow/skip. Other algorithms rely on generate_interior's
            # own loud too-small guard.
            if algorithm == "roomcorridor" and (
                width < ROOMCORRIDOR_MIN_DIM or height < ROOMCORRIDOR_MIN_DIM
            ):
                raise ValueError(
                    f"region {node.id!r} algorithm 'roomcorridor' dims "
                    f"{width}x{height} are below ROOMCORRIDOR_MIN_DIM="
                    f"{ROOMCORRIDOR_MIN_DIM} (the room-placement retry loop "
                    f"degenerates to sparse/empty rooms below this floor). "
                    f"No silent shrink/grow/skip."
                )

            seed = _region_interior_seed(request.campaign_seed, request.expansion_id, node.id)
            # Degenerate-seed guard (carry-forward): generate_interior's braid
            # sub-seed is seed ^ 0x5EED → 0 at the fixed point. Refuse it loudly.
            if seed == _BRAID_FIXED_POINT:
                raise ValueError(
                    f"region {node.id!r} derived interior seed equals the braid "
                    f"fixed point 0x5EED ({_BRAID_FIXED_POINT}); the braid "
                    f"sub-seed (seed ^ 0x5EED) would degenerate to 0. Refusing "
                    f"to feed the braid its fixed point (No Silent Fallbacks)."
                )

            grid = generate_interior(
                algorithm,
                width=width,
                height=height,
                seed=seed,
                braid_ratio=braid_ratio,
                params=params or None,
            )
            # Story 52-2: emit the ADR-096 mask + derived block here, inside
            # the live dungeon.materialize.fill span context so the mask span
            # nests under it. _emit_mask is loud on empty grids (No Silent
            # Fallbacks); we let the ValueError propagate to the outer
            # try/except so the fill span carries the failure marker.
            mask = _emit_mask(grid)
            with dungeon_materialize_mask_span(
                region_id=node.id,
                grid_width=mask.block.grid_width,
                grid_height=mask.block.grid_height,
                cell_width=mask.block.cell_width,
                mask_sha=mask.mask_sha,
            ):
                pass
            fills[node.id] = RegionFill(
                region_id=node.id,
                algorithm=algorithm,
                width=width,
                height=height,
                braid_ratio=braid_ratio,
                grid=grid,
                mask=mask,
            )
    except ValueError as exc:
        # Lie-detector: surface the fill failure on the span before re-raise
        # so the GM panel sees it. No swallowing, no retry, no skip.
        span.set_attribute("error", str(exc))
        raise

    # Lie-detector success payload: the ACTUALLY-applied algorithm + dims +
    # braid_ratio per region (proving braid_ratio was not silently defaulted).
    regions_payload = [
        {
            "region_id": rf.region_id,
            "algorithm": rf.algorithm,
            "width": rf.width,
            "height": rf.height,
            "braid_ratio": rf.braid_ratio,
        }
        for rf in fills.values()
    ]
    span.set_attribute("regions", json.dumps(regions_payload, sort_keys=True))
    span.set_attribute("region_count", len(fills))

    return fills


class CurationError(RuntimeError):
    """The bounded one-shot SDK ``complete_with_tools`` curation pass failed.

    Raised loudly so the materialization transaction aborts — there is no
    fallback that ships the raw manifest stamped curated (spec §7 / No
    Silent Fallbacks). The curate span carries ``curated=false`` + a
    specific ``reason`` before this propagates so the GM panel sees it.
    """


def _resolve_look_for_theme(bundle: CookbookBundle, theme: Any, *, region_id: str) -> str:
    """Resolve a region's cookbook LOOK from its theme (the look→theme seam).

    `assemble_region` requires a ``look`` (a ``LookDef`` id). There is no
    ``look`` on ``DungeonTheme`` and none on ``MaterializationRequest`` /
    §12 knobs. The join key found by reconcile: a ``LookDef`` carries
    ``generator_binding`` (``depthfirst``/``cellular``/``prim``) and a
    ``DungeonTheme`` carries ``interior.algorithm`` — they are the SAME
    generator-family id. So a region's look is the LookDef whose
    ``generator_binding`` equals the region theme's ``interior.algorithm``.

    Fail loud (No Silent Fallbacks): if no look binds the theme's
    algorithm (e.g. a ``roomcorridor`` theme with no ``roomcorridor`` look
    in the shipped beneath_sunden ``looks.yaml``) raise a ``ValueError``
    naming the region/theme/algorithm. Never default to ``looks[0]``.
    """
    algorithm = theme.interior.algorithm
    matches = [lk.id for lk in bundle.looks if lk.generator_binding == algorithm]
    if not matches:
        raise ValueError(
            f"region {region_id!r} theme {theme.id!r} interior.algorithm "
            f"{algorithm!r} has no cookbook LOOK whose generator_binding "
            f"matches it (looks: "
            f"{ {lk.id: lk.generator_binding for lk in bundle.looks} }). "
            f"No silent fallback to looks[0] — author a look for this "
            f"generator family or retheme the region."
        )
    if len(matches) > 1:
        raise ValueError(
            f"region {region_id!r} theme {theme.id!r} algorithm {algorithm!r} "
            f"is bound by multiple looks {sorted(matches)} — ambiguous "
            f"look→theme seam; the cookbook must bind one look per "
            f"generator family. No silent first-match."
        )
    return matches[0]


def _build_curation_prompt(
    manifests: dict[str, RegionContentManifest],
    looks: dict[str, str],
) -> str:
    """One bounded prompt covering spec §7 'pass 1 content, pass 2
    creatures' in a SINGLE one-shot SDK ``complete_with_tools`` call
    (ADR-098: no tools mid-generation, no --resume). The model
    selects/refines to ship quality and returns a strict JSON verdict
    mirroring the manifest shape (so curation is auditable, not free-form
    prose)."""
    payload = {
        region_id: {
            "look": looks[region_id],
            "race": m.race,
            "cr_band": m.cr_band,
            "wandering_table": m.wandering_table,
            "big_bad": m.big_bad,
        }
        for region_id, m in manifests.items()
    }
    return (
        "You are curating one procedurally-assembled dungeon expansion for "
        "Beneath Sünden (grave, lethal, Moria-as-tragedy; no winking).\n"
        "PASS 1 (content): for each region keep the cohesive subset of the "
        "wandering table that fits the region's look and CR band; drop rows "
        "that read as noise. PASS 2 (creatures): tighten each kept row's "
        "telegraph to one grave, specific sentence. Keep the big_bad if "
        "present.\n"
        "Return ONLY strict JSON, no prose, of the shape: "
        '{"<region_id>": {"race": str, "cr_band": str, '
        '"wandering_table": [{"name": str, "cr": number, "xp": number, '
        '"type": str, "weight": number, "count": str, "telegraph": str}], '
        '"big_bad": {"name": str, "min_band": str} | null}}.\n'
        "Preserve every kept row's name/cr/xp/type verbatim (curation "
        "selects and refines telegraphs; it does not invent stats).\n\n"
        f"INPUT:\n{json.dumps(payload, sort_keys=True)}"
    )


def _parse_curation_verdict(text: str) -> dict[str, Any]:
    """Parse the curator's JSON verdict. Unparseable → loud CurationError
    (never a fallback to the raw manifest)."""
    stripped = text.strip()
    # Tolerate a ```json fence the model may wrap around the object.
    if stripped.startswith("```"):
        stripped = stripped.strip("`")
        if stripped.startswith("json"):
            stripped = stripped[4:]
        stripped = stripped.strip()
    try:
        verdict = json.loads(stripped)
    except json.JSONDecodeError as exc:
        raise CurationError(
            f"curation pass returned unparseable output (not JSON): {exc}; head={stripped[:200]!r}"
        ) from exc
    if not isinstance(verdict, dict):
        raise CurationError(
            f"curation verdict must be a JSON object keyed by region_id; "
            f"got {type(verdict).__name__}"
        )
    return verdict


def _classify_parse_failure(exc: Exception) -> str:
    """Map a curate-attempt failure to an ADR-106 Amendment A
    ``failure_kind`` ∈ {truncated, malformed, llm_error}. ``deadline`` is
    set by the caller (it is a timeout, not an exception of the call)."""
    if isinstance(exc, LlmClientError):
        return "llm_error"
    # CurationError from _parse_curation_verdict. "Unterminated string" is
    # the pingpong truncation signature; everything else (Expecting value,
    # non-dict, …) is malformed.
    return "truncated" if "Unterminated" in str(exc) else "malformed"


def _creatures_from_manifest(
    manifest: RegionContentManifest, bundle: CookbookBundle
) -> tuple[list[CuratedCreature], CuratedCreature | None]:
    """ADR-106 Amendment A Layer-2 degrade content: CR→Edge translate the
    deterministic pre-curation ``assemble_region`` manifest itself (clause
    9 — valid, complete, seed-reproducible). Same CR→Edge seam the curated
    path uses; sourced from the manifest, not a (failed) verdict.

    A manifest row/big_bad that cannot CR→Edge translate is the RETAINED
    ``CurationError`` carve-out (i): the assembled input is itself
    structurally invalid — a real upstream bug; never degrade a corrupt
    input into shipped content.
    """
    creatures: list[CuratedCreature] = []
    for row in manifest.wandering_table:
        if "cr" not in row:
            raise CurationError(
                f"assembled manifest wandering row {row!r} has no 'cr' — "
                f"the pre-curation manifest is itself invalid (Amendment A "
                f"carve-out i); cannot degrade a corrupt input"
            )
        creatures.append(
            CuratedCreature(
                name=str(row["name"]),
                creature_type=str(row.get("type", "")),
                telegraph=str(row.get("telegraph", "")),
                edge=_edge_from_cr(float(row["cr"])),
            )
        )
    big_bad: CuratedCreature | None = None
    if manifest.big_bad is not None:
        bb_cr = None
        if isinstance(manifest.big_bad, dict):
            bb_cr = manifest.big_bad.get("cr")
        if bb_cr is None:
            band = next(
                (b for b in bundle.affinities.cr_bands if b.id == manifest.cr_band),
                None,
            )
            if band is None:
                raise CurationError(
                    f"assembled manifest big_bad has no cr and cr_band "
                    f"{manifest.cr_band!r} is not in affinities.cr_bands — "
                    f"the pre-curation manifest is itself invalid "
                    f"(Amendment A carve-out i)"
                )
            bb_cr = band.cr_max
        bb_src = manifest.big_bad if isinstance(manifest.big_bad, dict) else {}
        big_bad = CuratedCreature(
            name=str(bb_src.get("name", "")),
            creature_type="big_bad",
            telegraph=str(bb_src.get("min_band", "")),
            edge=_edge_from_cr(float(bb_cr)),
        )
    return creatures, big_bad


def _degrade_region(
    *,
    region_id: str,
    manifest: RegionContentManifest,
    bundle: CookbookBundle,
    failure_kind: str,
    attempts: int,
    elapsed_ms: int,
    reason: str,
) -> tuple[list[CuratedCreature], CuratedCreature | None]:
    """ADR-106 Amendment A Layer 2 — LOUD degrade for one region: an
    ERROR-level log (No-Silent-Fallbacks: never a swallowed except) + a
    routed ``dungeon.curate.degraded`` span (clause-12 GM-panel lie
    detector) + the deterministic manifest content. The region is honest
    coal stamped ``curated=false``, never a raw-manifest-stamped-curated
    silent lie."""
    logger.error(
        "dungeon curate degraded region=%s failure_kind=%s attempts=%d "
        "elapsed_ms=%d reason=%s — shipping the deterministic "
        "assemble_region manifest stamped curated=false (ADR-106 "
        "Amendment A Layer 2; turn proceeds, no table freeze)",
        region_id,
        failure_kind,
        attempts,
        elapsed_ms,
        reason,
    )
    with dungeon_curate_degraded_span(
        region_id=region_id,
        failure_kind=failure_kind,
        attempts=attempts,
        elapsed_ms=elapsed_ms,
    ):
        pass
    return _creatures_from_manifest(manifest, bundle)


async def _stage_curate(
    request: MaterializationRequest,
    *,
    bundle: CookbookBundle | None,
    palette: ThemePalette | None,
    expansion: Expansion | None,
    fill_result: dict[str, RegionFill] | None,
    is_first_band_entry: bool,
    claude_client: Any,
    span: _otel_trace.Span,
) -> RegionCuration:
    """Plan 7 Task 4: curate stage — assemble_region + one-shot SDK
    ``complete_with_tools`` + the owned CR→Edge seam.

    Generation proposes; curation disposes. For every region in the
    expansion: derive its cookbook LOOK from its theme (the resolved
    look→theme seam), call the pure deterministic
    ``cookbook.assemble_region`` (campaign_seed/expansion_id int→str at
    this seam — DIVERGENCE 1), then run ONE bounded one-shot SDK
    ``complete_with_tools`` pass (ADR-098 one-shot; spec §7 pass1+pass2 in
    a single call, the codebase-idiomatic SDK precedent) to select/refine
    to ship quality. Every corpus creature crossing the seam (wandering
    rows AND big_bad) is CR→Edge translated via the single canonical
    ``creature_edge_pool_from_hp`` — no raw cr/hp leaks into the
    curate-stage OUTPUT (so Task 6 commits Edge-only).

    ``async def``: ``complete_with_tools`` is a coroutine and the event
    loop is owned by the caller (uvicorn in prod, pytest-asyncio
    ``asyncio_mode=auto`` in tests). There is NO ``asyncio.run`` anywhere
    in production — a nested ``asyncio.run`` from the running uvicorn loop
    (and from Task 7's async look-ahead worker) would raise
    ``RuntimeError`` unconditionally. The other four stages stay
    synchronous; only curate awaits.

    Invariants (No Silent Fallbacks):
    - ``bundle``/``palette``/``expansion``/``claude_client`` must be real
      objects — ``None`` is rejected loudly.
    - A region's cookbook LOOK is ALWAYS derived loudly from its theme
      (``_resolve_look_for_theme`` — an unresolved look is a loud
      ``ValueError``; NEVER a ``looks[0]`` default; a multi-bind is also
      a loud ``ValueError``). There is no caller ``look`` override:
      the theme is the single source of truth.
    - ``is_first_band_entry`` is an EXPLICIT threaded input — true
      band-entry history needs Plan 5 persistence (``load_frontier`` /
      ``load_map``) the curate stage does NOT own. Computing it from
      incomplete state here would be a silent fallback; Task 6 (commit,
      which owns persistence) owns the real band-entry-history
      computation. (Reconcile seam: ``is_first_band_entry``.)
    - A curation LLM-call failure (``LlmClientError`` — network / API /
      empty) OR an unparseable verdict raises a loud ``CurationError``
      and aborts the transaction — it does NOT fall back to shipping the
      raw manifest stamped curated. The span records ``curated=false`` +
      a specific ``reason`` before the raise (lie-detector visibility).
    """
    if bundle is None:
        raise ValueError(
            "_stage_curate requires a real CookbookBundle — "
            "bundle=None is not valid (No Silent Fallbacks)"
        )
    if palette is None:
        raise ValueError(
            "_stage_curate requires a real ThemePalette — "
            "palette=None is not valid (No Silent Fallbacks)"
        )
    if expansion is None:
        raise ValueError(
            "_stage_curate requires a real Expansion — "
            "expansion=None is not valid (No Silent Fallbacks)"
        )
    if fill_result is None:
        # Required to enforce fill-ran-before-curate pipeline ordering;
        # consumed at Task 6 (commit), not read in this stage's body.
        raise ValueError(
            "_stage_curate requires the fill stage result — "
            "fill_result=None is not valid (No Silent Fallbacks)"
        )
    if claude_client is None:
        raise ValueError(
            "_stage_curate requires an injected SDK client "
            "(ToolingLlmClient) — claude_client=None is not valid "
            "(No Silent Fallbacks)"
        )

    campaign_seed_s = str(request.campaign_seed)  # DIVERGENCE 1: int→str seam
    expansion_id_s = str(request.expansion_id)  # DIVERGENCE 1: int→str seam
    depth_score = request.frontier_edge.spawn_depth_score

    manifests: dict[str, RegionContentManifest] = {}
    region_look: dict[str, str] = {}
    try:
        for node in expansion.new_nodes:
            if node.theme not in palette.themes:
                raise ValueError(
                    f"region {node.id!r} references theme {node.theme!r} "
                    f"which is absent from the palette (have: "
                    f"{sorted(palette.themes)}). No silent default theme."
                )
            theme = palette.themes[node.theme]
            # The look→theme seam: a region's cookbook LOOK is derived
            # loudly from its theme — the theme is the single source of
            # truth (No Silent Fallbacks — an unresolved or multi-bound
            # look raises in _resolve_look_for_theme; never a looks[0]
            # default, never a first-match).
            resolved_look = _resolve_look_for_theme(bundle, theme, region_id=node.id)
            region_look[node.id] = resolved_look
            manifests[node.id] = assemble_region(
                bundle,
                campaign_seed=campaign_seed_s,
                expansion_id=expansion_id_s,
                depth_score=depth_score,
                burst_magnitude=request.burst_magnitude,
                look=resolved_look,
                is_first_band_entry=is_first_band_entry,
            )
    except ValueError as exc:
        span.set_attribute("curated", False)
        span.set_attribute("reason", f"assemble: {exc}")
        raise

    # ADR-106 Amendment A — Curate-stage robustness contract (story 50-26).
    # Layer 0: max_tokens=16384 (retained, b846544). Layer 1: ONE bounded
    # whole-call retry (exactly 2 attempts) under a wall-clock cap
    # (CURATE_DEADLINE_S). Layer 2: LOUD degrade-to-uncurated — ship the
    # deterministic assemble_region manifest stamped curated=false, with a
    # per-region uncurated marker, an ERROR log, and a routed
    # dungeon.curate.degraded span; the turn proceeds (no table freeze).
    # CurationError is RETAINED only for the two carve-outs: (i) the
    # assembled manifest itself invalid (_creatures_from_manifest), (ii) a
    # parsed curated row missing 'cr' (degrading would corrupt the CR→Edge
    # seam). complete_with_tools is a coroutine; the loop is owned by the
    # caller (uvicorn / pytest) — NO asyncio.run. Each attempt is an
    # independent one-shot (ADR-098: no --resume, no mid-gen tools, no
    # continuation, NOT JSON repair — the truncated tail is never invented).
    prompt = _build_curation_prompt(manifests, region_look)
    system_blocks = [
        CacheableBlock(
            text=(
                "You curate procedural dungeon regions: select and refine "
                "each region's creatures, CR band, wandering table, and "
                "telegraphs. Reply with the verdict JSON only."
            ),
            cache=False,
        )
    ]
    region_ids_repr = ",".join(sorted(manifests))
    started = time.monotonic()

    async def _one_attempt() -> dict[str, Any]:
        result = await claude_client.complete_with_tools(
            system_blocks=system_blocks,
            messages=[Message(role="user", content=prompt)],
            tools=[],
            tool_dispatch=None,
            model=resolve_model(CallType.SCRATCH),
            max_tokens=16384,  # Layer 0 (retained)
        )
        return _parse_curation_verdict(result.text)

    verdict: dict[str, Any] | None = None
    attempts = 0
    degrade_kind = "malformed"
    degrade_reason = "curate verdict never parsed"
    try:
        async with asyncio.timeout(CURATE_DEADLINE_S):
            for attempt in range(1, 3):  # Layer 1: exactly 1 retry
                attempts = attempt
                try:
                    verdict = await _one_attempt()
                    break
                except (LlmClientError, CurationError) as exc:
                    degrade_kind = _classify_parse_failure(exc)
                    degrade_reason = str(exc)
                    with dungeon_curate_parse_failed_span(
                        region_id=region_ids_repr,
                        failure_kind=degrade_kind,
                        attempt=attempt,
                    ):
                        pass
    except TimeoutError:
        degrade_kind = "deadline"
        degrade_reason = f"curate exceeded the {CURATE_DEADLINE_S}s wall-clock cap"
        attempts = attempts or 1

    elapsed_ms = int((time.monotonic() - started) * 1000)

    region_creatures: dict[str, list[CuratedCreature]] = {}
    region_big_bad: dict[str, CuratedCreature | None] = {}
    uncurated: set[str] = set()

    if verdict is None:
        # Layer 1 exhausted (2 failed attempts) OR the wall-clock cap fired
        # → Layer 2 LOUD degrade for EVERY region. No raise, no frozen turn.
        for region_id, manifest in manifests.items():
            creatures, big_bad = _degrade_region(
                region_id=region_id,
                manifest=manifest,
                bundle=bundle,
                failure_kind=degrade_kind,
                attempts=attempts,
                elapsed_ms=elapsed_ms,
                reason=degrade_reason,
            )
            region_creatures[region_id] = creatures
            region_big_bad[region_id] = big_bad
            uncurated.add(region_id)
    else:
        # The verdict PARSED. Per-region isolation: a structurally-invalid
        # region degrades THAT region loudly; siblings stay curated (one
        # bad region never aborts the expansion). A curated row missing
        # 'cr' is the RETAINED CurationError carve-out (ii) — it RAISES,
        # it does NOT degrade (degrading would corrupt the CR→Edge seam).
        for region_id, manifest in manifests.items():
            rv = verdict.get(region_id)
            kept_rows = rv.get("wandering_table") if isinstance(rv, dict) else None
            if not isinstance(rv, dict) or not isinstance(kept_rows, list):
                creatures, big_bad = _degrade_region(
                    region_id=region_id,
                    manifest=manifest,
                    bundle=bundle,
                    failure_kind="malformed",
                    attempts=attempts,
                    elapsed_ms=elapsed_ms,
                    reason=(
                        f"region {region_id!r} verdict is not an object with "
                        f"a wandering_table list (got {type(rv).__name__})"
                    ),
                )
                region_creatures[region_id] = creatures
                region_big_bad[region_id] = big_bad
                uncurated.add(region_id)
                continue
            creatures = []
            for row in kept_rows:
                if "cr" not in row:
                    # RETAINED carve-out (ii): NOT degradable.
                    span.set_attribute("curated", False)
                    span.set_attribute(
                        "reason", f"curated row for {region_id!r} dropped 'cr'"
                    )
                    raise CurationError(
                        f"curated row for {region_id!r} dropped the 'cr' "
                        f"field ({row!r}); CR→Edge translation is impossible "
                        f"— the curator must preserve cr verbatim (ADR-106 "
                        f"Amendment A retained carve-out ii: NOT degraded, "
                        f"degrading would corrupt mechanics)"
                    )
                creatures.append(
                    CuratedCreature(
                        name=str(row["name"]),
                        creature_type=str(row.get("type", "")),
                        telegraph=str(row.get("telegraph", "")),
                        edge=_edge_from_cr(float(row["cr"])),
                    )
                )
            region_creatures[region_id] = creatures

            bb_v = rv.get("big_bad")
            if bb_v is None:
                region_big_bad[region_id] = None
            else:
                # The cookbook big_bad row is {name, min_band} only — no cr.
                # Source its CR from the manifest's raw big_bad if present;
                # otherwise the band ceiling (the capstone is a lair boss,
                # spec §4.2 big_bad_forces_size). Either way it crosses the
                # SAME CR→Edge seam — never a raw cr/hp.
                bb_cr = None
                if isinstance(manifest.big_bad, dict):
                    bb_cr = manifest.big_bad.get("cr")
                if bb_cr is None:
                    band = next(
                        (b for b in bundle.affinities.cr_bands if b.id == manifest.cr_band),
                        None,
                    )
                    if band is None:
                        raise CurationError(
                            f"big_bad for {region_id!r} has no cr and its "
                            f"cr_band {manifest.cr_band!r} is not in "
                            f"affinities.cr_bands — cannot CR→Edge translate"
                        )
                    bb_cr = band.cr_max
                region_big_bad[region_id] = CuratedCreature(
                    name=str(bb_v.get("name", "")),
                    creature_type="big_bad",
                    telegraph=str(bb_v.get("min_band", "")),
                    edge=_edge_from_cr(float(bb_cr)),
                )

    # Lie-detector summary on the curate STAGE span. `curated` is the
    # expansion rollup: False whenever any region Layer-2-degraded (never a
    # raw-manifest-stamped-curated lie — the forbidden silent fallback).
    curated = len(uncurated) == 0
    total_creatures = sum(len(v) for v in region_creatures.values())
    races = sorted({m.race for m in manifests.values()})
    bands = sorted({m.cr_band for m in manifests.values()})
    span.set_attribute("curated", curated)
    if not curated:
        span.set_attribute(
            "reason",
            f"degraded {sorted(uncurated)} (failure_kind={degrade_kind}): "
            f"{degrade_reason}",
        )
    span.set_attribute("region_count", len(manifests))
    span.set_attribute("creature_count", total_creatures)
    span.set_attribute("manifest_race", json.dumps(races, sort_keys=True))
    span.set_attribute("cr_band", json.dumps(bands, sort_keys=True))
    span.set_attribute("raw_seed_reproducible", False)

    return RegionCuration(
        region_manifests=manifests,
        region_creatures=region_creatures,
        region_big_bad=region_big_bad,
        region_look=region_look,
        curated=curated,
        raw_seed_reproducible=False,
        uncurated_regions=frozenset(uncurated),
    )


@dataclass(frozen=True, slots=True)
class AttachResult:
    """In-memory result of the attach stage (Plan 7 Task 5).

    A frozen, slotted value object — same idiom as Task 1's
    ``MaterializationRequest`` / Task 3's ``RegionFill`` / Task 4's
    ``RegionCuration``. Carries the two things Task 6 (commit) needs and
    must NEVER recompute (spec §7 save-is-truth freeze):

    * ``depth_report`` — the :class:`DepthReport` from
      ``assign_depth_scores`` (the byte-pinned ``dungeon.materialize.attach``
      span contract; the depth_score gradient is already frozen onto
      ``graph.nodes`` in place — this is the summary report).
    * ``attach_reports`` — one :class:`AttachReport` per (region, set_piece)
      that was attached. Each carries ``report.rolled`` (a
      ``RolledSetPiece``) — the spec §7 FREEZE TARGET Task 6 persists into
      the save and NEVER recomputes from seed.

    Note: ``frozen`` blocks field reassignment but ``attach_reports`` is a
    mutable list; treat it as read-only by convention (same
    false-immutability caveat as ``RegionFill.grid`` /
    ``RegionCuration``'s dict fields).

    The attach stage does NOT commit and does NOT roll back — Task 6 owns
    the transaction boundary (spec §7.5). Threads written by
    ``attach_set_piece`` live in the caller's UNCOMMITTED connection.
    """

    depth_report: DepthReport
    attach_reports: list[AttachReport]


def _stage_attach(
    request: MaterializationRequest,
    *,
    graph: RegionGraph | None,
    expansion: Expansion | None,
    palette: ThemePalette | None,
    curation: RegionCuration | None,
    snapshot: GameSnapshot | None,
    pack_tropes: Any,
    persistence: DungeonStore | None,
    span: _otel_trace.Span,
) -> AttachResult:
    """Plan 7 Task 5: attach stage — region-graph attach + depth scoring +
    the Plan 6 set-piece / trope / quest seam.

    Ordering (the plan owns this — Plan 6/5 spans nest INSIDE this span):
      1. ``attach_expansion(graph, expansion)`` — mutates + re-verifies the
         GLOBAL connected + loopful invariants. If it raises (a global
         invariant violation), the WHOLE materialization aborts: NO depth
         scoring, NO set-piece attach, NO partial state. The failure marker
         is routed onto the span before re-raise (lie-detector visibility).
      2. ``assign_depth_scores(graph, campaign_seed=...)`` → ``DepthReport``.
         The entrance scores to EXACTLY ``0.0`` (no jitter at the origin);
         an already-scored region is FROZEN (never recomputed — the save is
         truth, spec §7; ``assign_depth_scores`` enforces this). The span's
         attributes are set to EXACTLY ``DepthReport.as_dict()``'s 4 keys
         (byte-pinned GM-panel contract — NOT ``AttachReport``; that is
         Plan 6's nested ``setpiece.attach`` span).
      3. For every region in ``expansion.new_nodes``, resolve
         ``theme = palette.themes[node.theme]`` (loud raise if absent — no
         silent default theme) and for every ``set_piece in
         theme.set_pieces`` call Plan 6's single coalescence entry point
         ``attach_set_piece(...)`` with ``started_at_depth_score`` = the
         region's depth_score AFTER step 2, ``manifest`` = the curate
         stage's per-region ``RegionContentManifest``, accumulating
         ``threads_already_lit`` across ALL set-pieces in the WHOLE
         expansion. ``attach_set_piece`` emits its own
         ``setpiece.attach``/``trope.start``/``quest.seed`` spans and Plan 5
         emits ``ledger.add`` — Plan 7 does NOT re-emit them; they nest
         INSIDE this ``dungeon.materialize.attach`` span automatically.

    Invariants (No Silent Fallbacks):
    - ``graph``/``expansion``/``palette``/``curation``/``snapshot``/
      ``persistence`` must be real objects — ``None`` is rejected loudly.
      ``pack_tropes`` is a duck-typed object (``.tropes``) threaded from the
      session (Task 7 sources it in production) — REQUIRED, no default.
    - A region whose ``theme`` is absent from ``palette.themes`` → loud
      ``ValueError`` (no skip, no default theme).
    - A region absent from ``curation.region_manifests`` → loud
      ``KeyError`` via ``RegionCuration``'s fail-loud contract is NOT used
      here (it has no manifests accessor); we index ``region_manifests``
      directly and a ``KeyError`` propagates loudly (curate must cover
      every region — pipeline-ordering contract).
    - ``attach_expansion`` / ``assign_depth_scores`` / ``attach_set_piece``
      loud raises propagate unchanged after a routed failure marker is set.

    Returns an :class:`AttachResult` carrying the ``DepthReport`` and the
    per-(region, set_piece) ``AttachReport``s (each with ``.rolled`` — the
    spec §7 freeze target Task 6 persists, NEVER recomputed here). The
    attach stage does NOT commit / does NOT roll back / does NOT apply to a
    save — that is Task 6 (commit).
    """
    if graph is None:
        raise ValueError(
            "_stage_attach requires a real RegionGraph — "
            "graph=None is not valid (No Silent Fallbacks)"
        )
    if expansion is None:
        raise ValueError(
            "_stage_attach requires a real Expansion — "
            "expansion=None is not valid (No Silent Fallbacks)"
        )
    if palette is None:
        raise ValueError(
            "_stage_attach requires a real ThemePalette — "
            "palette=None is not valid (No Silent Fallbacks)"
        )
    if curation is None:
        raise ValueError(
            "_stage_attach requires the curate stage result — "
            "curation=None is not valid (No Silent Fallbacks)"
        )
    if snapshot is None:
        raise ValueError(
            "_stage_attach requires a real GameSnapshot — "
            "snapshot=None is not valid (No Silent Fallbacks). Production "
            "sourcing is the Task-7 session-wiring concern."
        )
    if pack_tropes is None:
        raise ValueError(
            "_stage_attach requires the resolved genre-pack tropes — "
            "pack_tropes=None is not valid (No Silent Fallbacks). "
            "Production sourcing is the Task-7 session-wiring concern."
        )
    if persistence is None:
        raise ValueError(
            "_stage_attach requires a real DungeonStore — "
            "persistence=None is not valid (No Silent Fallbacks)"
        )

    # Step 1: attach_expansion — mutates + re-verifies the GLOBAL
    # connected + loopful invariants. A loud raise here ABORTS the whole
    # materialization: no depth scoring, no set-piece attach, no partial
    # state. Route the failure marker onto the span before re-raise.
    try:
        attach_expansion(graph, expansion)
    except (ValueError, KeyError) as exc:
        span.set_attribute("error", str(exc))
        span.set_attribute("reason", f"attach_expansion: {exc}")
        raise

    # Step 2: assign_depth_scores — entrance == 0.0 (no jitter), frozen
    # (already-scored regions never recomputed — spec §7). A to-be-scored
    # region unreachable on the ordinary route raises loudly.
    try:
        depth_report = assign_depth_scores(graph, campaign_seed=request.campaign_seed)
    except (ValueError, KeyError) as exc:
        span.set_attribute("error", str(exc))
        span.set_attribute("reason", f"assign_depth_scores: {exc}")
        raise

    # Byte-pinned span attribute contract: EXACTLY DepthReport.as_dict()'s
    # 4 scalar keys (NOT AttachReport — that is Plan 6's nested span).
    for k, v in depth_report.as_dict().items():
        span.set_attribute(k, v)

    # Step 3: for each region's theme, call Plan 6's coalescence entry point.
    # threads_already_lit accumulates across ALL set-pieces in the WHOLE
    # expansion (expansion-level budget — initialised once, never per-region).
    attach_reports: list[AttachReport] = []
    threads_already_lit = 0
    try:
        for node in expansion.new_nodes:
            if node.theme not in palette.themes:
                raise ValueError(
                    f"region {node.id!r} references theme {node.theme!r} "
                    f"which is absent from the palette (have: "
                    f"{sorted(palette.themes)}). No silent default theme."
                )
            theme = palette.themes[node.theme]
            # curate must cover every region (pipeline-ordering contract);
            # a missing manifest is a loud KeyError, not a silent default.
            manifest = curation.region_manifests[node.id]
            # depth_score AFTER assign_depth_scores ran (REQUIRED, no
            # default — Decision I in setpiece_attach).
            started_at_depth_score = graph.nodes[node.id].depth_score
            if started_at_depth_score is None:
                raise ValueError(
                    f"region {node.id!r} has no depth_score after "
                    f"assign_depth_scores — cannot attach set-pieces "
                    f"(No Silent Fallbacks)"
                )
            for set_piece in theme.set_pieces:
                report = attach_set_piece(
                    campaign_seed=request.campaign_seed,
                    expansion_id=request.expansion_id,
                    region_id=node.id,
                    setpiece_id=set_piece.id,
                    set_piece=set_piece,
                    trope_components=set_piece.trope_components,
                    quest_components=set_piece.quest_components,
                    pack_tropes=pack_tropes,
                    snapshot=snapshot,
                    manifest=manifest,
                    store=persistence,
                    threads_lit_per_expansion=request.burst_magnitude,
                    threads_already_lit=threads_already_lit,
                    started_at_depth_score=started_at_depth_score,
                )
                threads_already_lit += report.threads_written
                attach_reports.append(report)
    except (ValueError, KeyError, PersistError) as exc:
        span.set_attribute("error", str(exc))
        span.set_attribute("reason", f"attach_set_piece: {exc}")
        raise

    return AttachResult(
        depth_report=depth_report,
        attach_reports=attach_reports,
    )


def _frontier_edge_id(campaign_seed: int, expansion_id: int, region_id: str) -> str:
    """Deterministic, collision-safe frontier-edge id.

    Mirrors ``setpiece_attach._thread_id_seed`` /
    ``region_graph.generator._subseed`` exactly: a pipe-delimited UTF-8
    string → ``blake2b(digest_size=8)`` → hex. NOT a uuid (a frontier
    re-derived from the same attached expansion must produce the SAME id
    so ``put_frontier``'s ``INSERT OR REPLACE`` is idempotent rather than
    duplicating rows). The house mixer; we do not invent a new scheme.
    """
    digest = hashlib.blake2b(
        f"frontier|{campaign_seed}|{expansion_id}|{region_id}".encode(),
        digest_size=8,
    ).digest()
    return f"fe_{digest.hex()}"


def _new_frontier_edges(
    request: MaterializationRequest,
    *,
    expansion: Expansion,
    graph: RegionGraph,
) -> list[FrontierEdge]:
    """Derive the new unexpanded frontier edges from the just-attached
    expansion (spec §7: "frontier — the set of unexpanded edges and the
    heading/depth_score an expansion there would spawn at").

    Each region node introduced by this expansion is a boundary from
    which a *future* expansion can be pushed outward — so each becomes a
    new unexpanded frontier edge:

    - ``from_region_id`` = the new region's id (the push-off point),
    - ``heading``        = the party's push heading (``request.heading``;
      the only directional signal the pipeline carries — spec §6's
      look-ahead "single approaching edge along the party's current
      heading"),
    - ``spawn_depth_score`` = that region's frozen ``depth_score`` after
      ``assign_depth_scores`` (the depth the *next* expansion off this
      region begins at — the gradient continues outward from here).

    No arbitrary edges are invented: every returned edge is anchored to a
    real ``expansion.new_nodes`` region whose depth_score the attach stage
    already froze onto ``graph.nodes`` (REQUIRED — a node with no
    depth_score is a loud reconcile failure, never a silent 0.0).
    """
    edges: list[FrontierEdge] = []
    for node in expansion.new_nodes:
        live = graph.nodes.get(node.id)
        if live is None:
            raise PersistError(
                f"new frontier edge derivation: region {node.id!r} is not in "
                f"the attached graph — commit must run after attach_expansion "
                f"(No Silent Fallbacks)"
            )
        if live.depth_score is None:
            raise PersistError(
                f"new frontier edge derivation: region {node.id!r} has no "
                f"depth_score after assign_depth_scores — cannot derive the "
                f"spawn_depth_score for the next expansion (No Silent "
                f"Fallbacks; never default to 0.0)"
            )
        edges.append(
            FrontierEdge(
                frontier_edge_id=_frontier_edge_id(
                    request.campaign_seed, request.expansion_id, node.id
                ),
                from_region_id=node.id,
                heading=request.heading,
                spawn_depth_score=live.depth_score,
            )
        )
    return edges


def _stage_commit(
    request: MaterializationRequest,
    *,
    graph: RegionGraph | None,
    expansion: Expansion | None,
    attach_result: AttachResult | None,
    persistence: DungeonStore | None,
    span: _otel_trace.Span,
) -> None:
    """Plan 7 Task 6: commit stage — one transaction, caller-owned
    boundary, seed-as-Expansion-0, rollback on PersistError.

    The whole materialized expansion **plus its started threads** is
    written to the live save in ONE Plan 5 transaction and is
    *immediately live* on success (spec §7.5). The caller (this stage)
    owns the transaction boundary — ``DungeonStore`` never autocommits.

    Sequence (all on ``persistence``'s connection, ONE txn):

    1. **Seed = Expansion 0** (loud fresh-save detection): production
       ``commit_expansion`` persists ONLY ``expansion.new_nodes``; the
       surface entrance has ``expansion_id == 0`` and belongs to NO
       generated ``Expansion.new_nodes``, so it is never persisted by a
       generated commit. On a *fresh* save (``load_map`` empty AND
       ``load_frontier`` empty — introspected loudly, never assumed) the
       entrance is committed first as
       ``Expansion(expansion_id=0, new_nodes=[entrance], new_edges=[])``
       (entrance ``depth_score`` is the frozen root ``0.0``). On a
       non-fresh save the entrance is already frozen — re-committing it
       would (correctly) raise the freeze ``PersistError``; so the seed
       commit runs ONLY when the save is genuinely fresh.
    2. ``commit_expansion(expansion, graph)`` — persists this expansion's
       ``new_nodes``/``new_edges`` (depth-scored nodes read from
       ``graph``). A re-commit of an already-frozen region raises
       ``PersistError`` (spec §7 freeze — frozen regions never rewritten).
    3. RECONCILE SEAM A — the spec §7 FREEZE TARGET ``AttachReport.rolled``
       (a ``RolledSetPiece``) is persisted-as-is via the real Plan 5
       append-only primitive ``record_mutation(region_id,
       kind="setpiece_state", payload=...)`` within this SAME txn.
       ``commit_expansion``'s node payload (``RegionNode.to_dict()``) has
       NO setpiece-state slot and the ``mask BLOB`` column is unwritten by
       Plan 5's API, so ``record_mutation`` is the faithful Plan-5 carrier.
       ``.rolled`` is persisted EXACTLY as the attach stage produced it
       and is NEVER recomputed here (save-is-truth).
    4. New unexpanded frontier edges (derived from the attached expansion
       — :func:`_new_frontier_edges`, no invented edges) are
       ``put_frontier``'d within the same txn.
    5. The complication-ledger rows are ALREADY in this uncommitted
       connection: Task 5's ``_stage_attach`` called
       ``attach_set_piece`` → ``store.open_thread`` on the same
       connection. Task 6 does NOT re-open threads; the txn it commits
       already contains them.

    On success the connection is committed (``conn.commit()``) → the
    expansion is immediately live. On ``PersistError`` (``commit_expansion``
    can write region A before region B's ``IntegrityError``; **SQLite does
    NOT auto-rollback**) the connection is rolled back
    (``conn.rollback()``) so NO half-attached expansion / NO orphan ledger
    rows survive — then the error re-raises loudly (No Silent Fallbacks).
    Either way a routed marker is set on the commit span (lie-detector
    visibility — the Task-2 lesson) and ``frontier.expand`` is emitted
    when the frontier is updated.

    Invariants (No Silent Fallbacks):
    - ``graph``/``expansion``/``attach_result``/``persistence`` must be
      real objects — ``None`` is rejected loudly.
    - Fresh-save detection is loud introspection, never an assumption.
    - ``PersistError`` → rollback + routed failure marker + re-raise; a
      partial/half-committed expansion is NEVER shipped.
    - ``AttachReport.rolled`` is persisted-as-is, NEVER recomputed.
    """
    if graph is None:
        raise ValueError(
            "_stage_commit requires a real RegionGraph — "
            "graph=None is not valid (No Silent Fallbacks)"
        )
    if expansion is None:
        raise ValueError(
            "_stage_commit requires a real Expansion — "
            "expansion=None is not valid (No Silent Fallbacks)"
        )
    if attach_result is None:
        raise ValueError(
            "_stage_commit requires the attach stage result — "
            "attach_result=None is not valid (No Silent Fallbacks); the "
            "AttachReport.rolled freeze targets must be threaded by identity"
        )
    if persistence is None:
        raise ValueError(
            "_stage_commit requires a real DungeonStore — "
            "persistence=None is not valid (No Silent Fallbacks)"
        )

    # RECONCILE NOTE (Plan-5-API vs spec prose): the merged Plan 5
    # DungeonStore exposes NO public commit()/rollback() — by deliberate
    # design the CALLER owns the connection + transaction boundary (spec
    # §7.5; persistence.py docstring; the Plan 5 test precedent calls
    # conn.commit()/conn.rollback() directly on the supplied connection,
    # test_persistence.py:173/340). The store stores exactly the
    # caller-supplied connection as ``_conn``. Task 6 is that caller, so it
    # drives the txn boundary on that same connection. There is no public
    # accessor to reach instead — this single private read IS the
    # documented caller-owned-boundary seam, not an encapsulation break.
    conn = persistence._conn

    # Loud fresh-save detection (introspection, NOT an assumption): a
    # save is fresh iff the dungeon map AND frontier are both empty. On a
    # fresh save the surface entrance has never been persisted (it belongs
    # to no generated Expansion.new_nodes) so we must seed it as
    # Expansion 0 before the first generated expansion is committed.
    existing_map = persistence.load_map(entrance_id=graph.entrance_id)
    existing_frontier = persistence.load_frontier()
    is_fresh_save = not existing_map.nodes and not existing_frontier

    new_frontier = _new_frontier_edges(request, expansion=expansion, graph=graph)

    # Resolve the generator version at COMMIT time, not at import time.
    # commit_expansion's `generator_version=GENERATOR_VERSION` default is
    # bound once at def-time; passing the current module global explicitly
    # honours a mid-campaign version bump so a genuinely never-materialized
    # expansion uses the new code while frozen regions stay frozen (spec
    # §7 "only never-materialized expansions use new code"). Read the live
    # module attribute (lazy-import idiom — the session.py watcher_hub
    # precedent — so a mid-campaign bump is observed, not the def-time
    # binding).
    from sidequest.dungeon import persistence as _live_persistence

    generator_version = _live_persistence.GENERATOR_VERSION

    try:
        if is_fresh_save:
            entrance = graph.nodes.get(graph.entrance_id)
            if entrance is None:
                raise PersistError(
                    f"Seed=Expansion-0: entrance {graph.entrance_id!r} is not "
                    f"in the graph — cannot seed a fresh save (No Silent "
                    f"Fallbacks)"
                )
            persistence.commit_expansion(
                Expansion(expansion_id=0, new_nodes=[entrance], new_edges=[]),
                graph,
                generator_version=generator_version,
            )

        persistence.commit_expansion(expansion, graph, generator_version=generator_version)

        # RECONCILE SEAM A: persist the spec §7 freeze target
        # AttachReport.rolled EXACTLY as attach produced it (never
        # recomputed) via the real Plan 5 append-only primitive. One
        # mutation row per (region, set-piece) attach report.
        rolled_persisted = 0
        for report in attach_result.attach_reports:
            persistence.record_mutation(
                report.region_id,
                "setpiece_state",
                {
                    "setpiece_id": report.setpiece_id,
                    "region_id": report.region_id,
                    "rolled": dict(report.rolled.slots),
                },
            )
            rolled_persisted += 1

        for fe in new_frontier:
            persistence.put_frontier(fe)

        conn.commit()
    except PersistError as exc:
        # SQLite does NOT auto-rollback a mid-write IntegrityError:
        # commit_expansion can write region A before region B's
        # IntegrityError. Roll back the WHOLE txn so no half-attached
        # expansion / orphan ledger row survives, then re-raise loudly.
        conn.rollback()
        span.set_attribute("error", str(exc))
        span.set_attribute("reason", f"commit: {exc}")
        raise

    # Lie-detector success summary on the commit span (the design/attach
    # precedent: a real success summary, not just the pre-baked stage).
    span.set_attribute("expansion_id", request.expansion_id)
    span.set_attribute("seeded_entrance", is_fresh_save)
    span.set_attribute("regions_committed", len(expansion.new_nodes))
    span.set_attribute("edges_committed", len(expansion.new_edges))
    span.set_attribute("rolled_persisted", rolled_persisted)
    span.set_attribute("frontier_edges_added", len(new_frontier))
    span.set_attribute("generator_version", generator_version)

    # Plan 7 owns frontier.expand: emit one per new unexpanded frontier
    # edge so the GM panel sees the dungeon's frontier actually grew (the
    # OTEL Observability Principle — the frontier update must be
    # observable, not just asserted by narration).
    for fe in new_frontier:
        with frontier_expand_span(
            expansion_id=request.expansion_id,
            frontier_edge_id=fe.frontier_edge_id,
            from_region_id=fe.from_region_id,
            heading=fe.heading,
            spawn_depth_score=fe.spawn_depth_score,
        ):
            pass


# ---------------------------------------------------------------------------
# Coordinator
# ---------------------------------------------------------------------------


async def materialize(
    request: MaterializationRequest,
    *,
    graph: RegionGraph | None,
    bundle: Any,
    palette: Any,
    persistence: DungeonStore,
    snapshot: GameSnapshot,
    pack_tropes: Any,
    claude_client: Any,
    is_first_band_entry: bool = True,
) -> None:
    """Run the five-stage materialisation pipeline for one expansion.

    Opens a parent ``dungeon.materialize`` OTEL span; each of the five stage
    spans nests under it in order (design → fill → curate → attach → commit).

    Stages design/fill/curate are implemented (Plan 7 Tasks 2–4); attach
    and commit remain ``NotImplementedError`` until Plan 7 Tasks 5–6.

    ``async def``: the curate stage awaits the SDK
    ``complete_with_tools``. The event loop is owned by the caller
    (uvicorn in prod, pytest-asyncio ``asyncio_mode=auto`` in tests) —
    there is NO ``asyncio.run`` anywhere, so Task 7's async look-ahead
    worker can ``await materialize()`` directly from inside its
    coroutine. design/fill/attach/commit remain plain synchronous calls
    inside this async coordinator; only curate is awaited.

    Parameters
    ----------
    request:
        Frozen expansion specification. ``request.expansion_id`` must be >= 1.
    graph:
        The live ``RegionGraph`` (passed through to attach/commit stages).
    bundle:
        The cookbook bundle (consumed by the curate stage).
    palette:
        The ``ThemePalette`` (consumed by design/fill/curate).
    persistence:
        The ``DungeonStore`` operating on the live save-DB connection
        (caller owns the transaction boundary, spec §7.5).
    snapshot:
        The live ``GameSnapshot`` — the attach stage's
        ``attach_set_piece`` call mutates ``snapshot.active_tropes`` for
        every started trope component (ADR-018 seam). REQUIRED, no silent
        default. Production sourcing (the live session snapshot) is the
        Task-7 session-wiring concern; Task 5 binds the API.
        (Reconcile seam: ``snapshot``.)
    pack_tropes:
        The resolved genre-pack tropes (a duck-typed object with
        ``.tropes``, ADR-018) threaded into the attach stage's
        ``attach_set_piece`` call so trope_ids resolve against the pack.
        REQUIRED, no silent default. Production sourcing (the resolved
        genre-pack) is the Task-7 session-wiring concern; Task 5 binds the
        API. (Reconcile seam: ``pack_tropes``.)
    claude_client:
        Required. The session supplies the SDK client
        (``build_llm_client()`` default ``AnthropicSdkClient``); the
        curate stage issues a one-shot ``complete_with_tools``. Tests
        inject a ``ToolingLlmClient``-shaped fake so no real network call
        is made (DI discipline mirrored from the rest of the codebase —
        NOT a hardcoded non-injectable client; No Silent Fallbacks —
        ``None`` raises, no implicit construction).
    is_first_band_entry:
        Caller-asserted band-entry flag threaded into the curate stage's
        ``assemble_region`` call. The TRUE band-entry-history computation
        needs Plan 5 persistence (``load_frontier``/``load_map``) that the
        curate stage does NOT own; it is deferred to Task 6 (commit, which
        owns persistence). For Task 4 the coordinator passes this
        caller-supplied value (NOT a silent default computed from
        incomplete state). (Reconcile seam: ``is_first_band_entry``.)
    """
    if claude_client is None:
        raise ValueError(
            "materialize requires an explicit claude_client (the look-ahead "
            "worker/session supplies the SDK client via build_llm_client(); "
            "No Silent Fallbacks — no implicit ClaudeClient())"
        )
    curation_client = claude_client

    # The per-region look is derived from each region's theme INSIDE
    # _stage_curate (it has bundle+palette+expansion) — the theme is the
    # single source of truth (loud raise on unresolvable/multi-bound;
    # never a silent default). No look value is threaded from here.
    with dungeon_materialize_span(
        expansion_id=request.expansion_id,
        heading=request.heading,
        burst_magnitude=request.burst_magnitude,
    ):
        with dungeon_materialize_design_span(expansion_id=request.expansion_id) as design_span:
            expansion, _report = _stage_design(
                request, graph=graph, palette=palette, span=design_span
            )

        with dungeon_materialize_fill_span(expansion_id=request.expansion_id) as fill_span:
            fill_result = _stage_fill(request, expansion=expansion, palette=palette, span=fill_span)

        with dungeon_materialize_curate_span(expansion_id=request.expansion_id) as curate_span:
            curation = await _stage_curate(
                request,
                bundle=bundle,
                palette=palette,
                expansion=expansion,
                fill_result=fill_result,
                is_first_band_entry=is_first_band_entry,
                claude_client=curation_client,
                span=curate_span,
            )

        with dungeon_materialize_attach_span(expansion_id=request.expansion_id) as attach_span:
            attach_result = _stage_attach(
                request,
                graph=graph,
                expansion=expansion,
                palette=palette,
                curation=curation,
                snapshot=snapshot,
                pack_tropes=pack_tropes,
                persistence=persistence,
                span=attach_span,
            )

        with dungeon_materialize_commit_span(expansion_id=request.expansion_id) as commit_span:
            # Thread the attach stage's AttachResult into commit: its
            # ``attach_reports[].rolled`` is the spec §7 freeze target Task
            # 6 PERSISTS and NEVER recomputes (save-is-truth). Discarding
            # it here would force Task 6 to re-roll. ``expansion``/``graph``
            # carry the depth-scored attached topology commit_expansion +
            # new-frontier-edge derivation read. ``_stage_commit`` is SYNC
            # (commit_expansion/put_frontier are sync) — a plain call inside
            # this async coordinator, never awaited.
            _stage_commit(
                request,
                graph=graph,
                expansion=expansion,
                attach_result=attach_result,
                persistence=persistence,
                span=commit_span,
            )
