"""Tests for sidequest.game.tension_tracker — dual-track pacing model.

Port of ``sidequest-api/crates/sidequest-game/src/tension_tracker.rs``.

Port discipline (per ADR-082 / Epic 42 execution-strategy spec):

- Every Rust ``#[test]`` becomes one pytest function with the same name.
- No idiomatic rewrites — Rust source is the behavioural contract.
- Classification-table parity is enforced via JSON fixtures generated by
  the Rust example at
  ``sidequest-api/crates/sidequest-game/examples/tension_fixture_export.rs``.
  Regenerate with ``cargo run --example tension_fixture_export``.
- Multi-round scenarios (escalating, stalling, reversal) are full
  observe→pacing_hint sequences captured from Rust as committed JSON;
  the Python port replays them step-for-step and asserts every
  intermediate state matches.

The Python ``TensionTracker`` API mirrors Rust:

- ``TensionTracker()`` / ``TensionTracker.with_values(action, stakes)``
- ``action_tension() / stakes_tension() / drama_weight() / active_spike() / boring_streak()``
- ``inject_spike(amount)``
- ``record_event(CombatEvent)``
- ``update_stakes(current_hp, max_hp)``
- ``tick()``  (no args — decays action_tension and ages spike)
- ``observe(round, killed, lowest_hp_ratio) -> TurnClassification``
- ``pacing_hint(thresholds: DramaThresholds) -> PacingHint``

Free functions:

- ``classify_round(round, killed) -> CombatEvent``
- ``classify_combat_outcome(round, killed, lowest_hp_ratio) -> TurnClassification``

Spec deviations vs context-story-42-3.md (logged in session file):

- AC2 names ``tracker.tick(round_result)``; Rust API is
  ``observe(round, killed, lowest_hp_ratio)`` then ``pacing_hint(thresholds)``.
- AC3 zone is ``AttentionZone.Late`` (Rust source), not Early/Valley.
- ``TurnContext.pacing_hint`` is typed ``PacingHint | None``, not ``str | None``.
"""

from __future__ import annotations

import json
import math
from pathlib import Path

import pytest

from sidequest.game.tension_tracker import (
    CombatEvent,
    DamageEvent,
    DeliveryMode,
    DetailedCombatEvent,
    RoundResult,
    TensionTracker,
    TurnClassification,
    classify_combat_outcome,
    classify_round,
)
from sidequest.genre.models.ocean import DramaThresholds

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


FIXTURE_DIR = Path(__file__).parent.parent / "fixtures" / "tension"


def _load_fixture(name: str) -> dict:
    path = FIXTURE_DIR / name
    with path.open(encoding="utf-8") as fh:
        return json.load(fh)


def _round_from_fixture(blob: dict) -> RoundResult:
    return RoundResult(
        round=blob["round"],
        damage_events=[
            DamageEvent(
                attacker=d["attacker"],
                target=d["target"],
                damage=d["damage"],
                round=d["round"],
            )
            for d in blob.get("damage_events", [])
        ],
        effects_applied=list(blob.get("effects_applied", [])),
        effects_expired=list(blob.get("effects_expired", [])),
    )


def _classification_from_fixture(blob: dict) -> TurnClassification:
    if blob["kind"] == "Boring":
        return TurnClassification.boring()
    if blob["kind"] == "Normal":
        return TurnClassification.normal()
    if blob["kind"] == "Dramatic":
        event_name = blob["event"]
        return TurnClassification.dramatic(DetailedCombatEvent[event_name])
    raise ValueError(f"unknown classification kind: {blob['kind']}")


def _approx(a: float, b: float, tol: float = 1e-9) -> bool:
    return math.isclose(a, b, rel_tol=tol, abs_tol=tol)


# =========================================================================
# Construction
# =========================================================================


def test_new_tracker_has_zero_tensions():
    tracker = TensionTracker()
    assert tracker.action_tension() == 0.0
    assert tracker.stakes_tension() == 0.0
    assert tracker.drama_weight() == 0.0


def test_new_with_initial_values():
    tracker = TensionTracker.with_values(0.3, 0.5)
    assert tracker.action_tension() == 0.3
    assert tracker.stakes_tension() == 0.5


def test_initial_values_clamped_to_unit_range():
    tracker = TensionTracker.with_values(1.5, -0.2)
    assert tracker.action_tension() == 1.0
    assert tracker.stakes_tension() == 0.0


# =========================================================================
# Action tension — gambler's ramp
# =========================================================================


def test_boring_turn_increases_action_tension():
    tracker = TensionTracker()
    tracker.record_event(CombatEvent.Boring)
    assert tracker.action_tension() > 0.0, "boring turn should ramp action tension"


def test_consecutive_boring_turns_ramp_faster():
    tracker = TensionTracker()
    tracker.record_event(CombatEvent.Boring)
    after_one = tracker.action_tension()
    tracker.record_event(CombatEvent.Boring)
    after_two = tracker.action_tension()
    assert (after_two - after_one) > after_one, (
        f"gambler's ramp should accelerate: first bump {after_one}, "
        f"second bump {after_two - after_one}"
    )


def test_dramatic_event_drops_action_tension():
    tracker = TensionTracker()
    for _ in range(5):
        tracker.record_event(CombatEvent.Boring)
    before = tracker.action_tension()
    tracker.record_event(CombatEvent.Dramatic)
    assert tracker.action_tension() < before, "dramatic event should drop action tension"


def test_dramatic_event_resets_boring_streak():
    tracker = TensionTracker()
    for _ in range(3):
        tracker.record_event(CombatEvent.Boring)
    tracker.record_event(CombatEvent.Dramatic)
    tracker.record_event(CombatEvent.Boring)
    fresh_boring = tracker.action_tension()
    fresh = TensionTracker()
    fresh.record_event(CombatEvent.Boring)
    assert fresh_boring == fresh.action_tension(), (
        "after dramatic reset, boring ramp should restart from scratch"
    )


# =========================================================================
# Stakes tension — HP-based
# =========================================================================


def test_damage_raises_stakes_tension():
    tracker = TensionTracker()
    tracker.update_stakes(80, 100)
    assert tracker.stakes_tension() > 0.0, "damage should raise stakes tension"


def test_low_hp_means_high_stakes():
    tracker = TensionTracker()
    tracker.update_stakes(10, 100)
    assert tracker.stakes_tension() > 0.8, (
        f"10% HP should yield very high stakes tension, got {tracker.stakes_tension()}"
    )


def test_full_hp_means_zero_stakes():
    tracker = TensionTracker()
    tracker.update_stakes(100, 100)
    assert tracker.stakes_tension() == 0.0, "full HP should mean zero stakes tension"


def test_healing_reduces_stakes_tension():
    tracker = TensionTracker()
    tracker.update_stakes(30, 100)
    before = tracker.stakes_tension()
    tracker.update_stakes(60, 100)
    assert tracker.stakes_tension() < before, "healing should reduce stakes tension"


def test_zero_hp_maxes_stakes():
    tracker = TensionTracker()
    tracker.update_stakes(0, 100)
    assert tracker.stakes_tension() == 1.0, "0 HP should be max stakes"


# =========================================================================
# Drama weight — combined metric
# =========================================================================


def test_drama_weight_is_max_of_both_tracks():
    tracker = TensionTracker.with_values(0.3, 0.7)
    assert tracker.drama_weight() == 0.7, "drama_weight should be max(action, stakes)"


def test_drama_weight_follows_action_when_higher():
    tracker = TensionTracker.with_values(0.9, 0.2)
    assert tracker.drama_weight() == 0.9, (
        "drama_weight should follow action_tension when it's higher"
    )


def test_drama_weight_includes_spike():
    tracker = TensionTracker()
    tracker.inject_spike(0.8)
    assert tracker.drama_weight() >= 0.8, (
        f"spike should boost drama_weight, got {tracker.drama_weight()}"
    )


# =========================================================================
# Spike injection and decay
# =========================================================================


def test_spike_injection_adds_temporary_boost():
    tracker = TensionTracker()
    tracker.inject_spike(0.6)
    assert tracker.active_spike() > 0.0, "injected spike should be visible"


def test_spike_decays_over_ticks():
    tracker = TensionTracker()
    tracker.inject_spike(0.8)
    initial_spike = tracker.active_spike()
    tracker.tick()
    assert tracker.active_spike() < initial_spike, "spike should decay after tick"


def test_spike_fully_decays_to_zero():
    tracker = TensionTracker()
    tracker.inject_spike(0.5)
    for _ in range(10):
        tracker.tick()
    assert tracker.active_spike() == 0.0, "spike should fully decay to 0.0"


def test_spike_clamped_to_unit_range():
    tracker = TensionTracker()
    tracker.inject_spike(1.5)
    assert tracker.active_spike() <= 1.0, "spike should be clamped to 1.0"


# =========================================================================
# Tension decay over quiet turns
# =========================================================================


def test_action_tension_decays_on_tick():
    tracker = TensionTracker.with_values(0.8, 0.0)
    tracker.tick()
    assert tracker.action_tension() < 0.8, "action tension should decay on tick without events"


def test_stakes_tension_does_not_decay_on_tick():
    tracker = TensionTracker.with_values(0.0, 0.6)
    tracker.tick()
    assert tracker.stakes_tension() == 0.6, (
        "stakes tension should NOT decay on tick (it's HP-driven)"
    )


def test_multiple_ticks_decay_toward_zero():
    tracker = TensionTracker.with_values(0.9, 0.0)
    for _ in range(50):
        tracker.tick()
    assert tracker.action_tension() < 0.01, (
        f"many quiet ticks should decay action tension near zero, got {tracker.action_tension()}"
    )


# =========================================================================
# Edge cases and clamping
# =========================================================================


def test_action_tension_never_exceeds_one():
    tracker = TensionTracker()
    for _ in range(100):
        tracker.record_event(CombatEvent.Boring)
    assert tracker.action_tension() <= 1.0, (
        f"action tension must stay <= 1.0, got {tracker.action_tension()}"
    )


def test_action_tension_never_goes_negative():
    tracker = TensionTracker()
    tracker.record_event(CombatEvent.Dramatic)
    assert tracker.action_tension() >= 0.0, "action tension must stay >= 0.0"


def test_drama_weight_clamped_with_spike():
    tracker = TensionTracker.with_values(0.9, 0.9)
    tracker.inject_spike(0.8)
    assert tracker.drama_weight() <= 1.0, (
        f"drama_weight should not exceed 1.0 even with spike, got {tracker.drama_weight()}"
    )


def test_both_tensions_at_max():
    tracker = TensionTracker.with_values(1.0, 1.0)
    assert tracker.drama_weight() == 1.0


def test_both_tensions_at_zero():
    tracker = TensionTracker.with_values(0.0, 0.0)
    assert tracker.drama_weight() == 0.0


# =========================================================================
# CombatEvent classification
# =========================================================================


def test_combat_event_variants_exist():
    # Ensure the enum has the expected string-stable values (StrEnum
    # members compare to their string value — this also catches a typo
    # in the variant declaration that ``is not None`` would miss).
    assert CombatEvent.Boring == "Boring"
    assert CombatEvent.Dramatic == "Dramatic"
    assert CombatEvent.Normal == "Normal"
    # And they are distinct.
    assert CombatEvent.Boring != CombatEvent.Dramatic
    assert CombatEvent.Boring != CombatEvent.Normal
    assert CombatEvent.Dramatic != CombatEvent.Normal


def test_normal_event_has_mild_effect_on_action_tension():
    tracker = TensionTracker()
    for _ in range(3):
        tracker.record_event(CombatEvent.Boring)
    before = tracker.action_tension()
    tracker.record_event(CombatEvent.Normal)
    assert tracker.action_tension() <= before, "normal event should not increase action tension"


# =========================================================================
# AC1 — Edge case: killed=None vs killed="" must behave identically
#         (both are "someone died" — kill-priority dramatic).
# =========================================================================


def test_classify_round_killed_empty_string_is_dramatic():
    """`killed = Some("")` in Rust → killed="" in Python. Still a kill."""
    rr = RoundResult(round=1, damage_events=[], effects_applied=[], effects_expired=[])
    assert classify_round(rr, killed="") == CombatEvent.Dramatic


def test_classify_round_killed_none_with_no_damage_is_boring():
    rr = RoundResult(round=1, damage_events=[], effects_applied=[], effects_expired=[])
    assert classify_round(rr, killed=None) == CombatEvent.Boring


def test_classify_combat_outcome_killed_empty_string_is_killing_blow():
    rr = RoundResult(round=1, damage_events=[], effects_applied=[], effects_expired=[])
    cls = classify_combat_outcome(rr, killed="", lowest_hp_ratio=None)
    assert cls == TurnClassification.dramatic(DetailedCombatEvent.KillingBlow)


# =========================================================================
# AC1 — Fixture parity: classify_round
# =========================================================================


def test_classify_round_fixture_parity():
    fixture = _load_fixture("classify_round.json")
    cases = fixture["cases"]
    assert len(cases) > 0, "fixture must have cases"

    failures = []
    for case in cases:
        round_result = _round_from_fixture(case["input"])
        killed = case["input"].get("killed")
        expected_name = case["expected"]
        actual = classify_round(round_result, killed)
        if actual.name != expected_name:
            failures.append(f"{case['name']}: expected {expected_name}, got {actual.name}")

    assert not failures, "classify_round parity drift:\n" + "\n".join(failures)


# =========================================================================
# AC1 — Fixture parity: classify_combat_outcome
# =========================================================================


def test_classify_combat_outcome_fixture_parity():
    fixture = _load_fixture("classify_combat_outcome.json")
    cases = fixture["cases"]
    assert len(cases) > 0, "fixture must have cases"

    failures = []
    for case in cases:
        round_result = _round_from_fixture(case["input"]["round"])
        killed = case["input"]["round"].get("killed")
        ratio = case["input"].get("lowest_hp_ratio")
        expected = _classification_from_fixture(case["expected"])
        actual = classify_combat_outcome(round_result, killed, ratio)
        if actual != expected:
            failures.append(f"{case['name']}: expected {expected!r}, got {actual!r}")

    assert not failures, "classify_combat_outcome parity drift:\n" + "\n".join(failures)


# =========================================================================
# AC2 — Multi-round scenario parity (escalating, stalling, reversal)
#       Each scenario file lists steps; replay against TensionTracker and
#       assert every intermediate state matches Rust output byte-for-byte.
# =========================================================================


def _replay_scenario(fixture_name: str) -> None:
    fixture = _load_fixture(fixture_name)
    th = DramaThresholds(**fixture["thresholds"])
    tracker = TensionTracker()

    # Guard against an empty fixture silently passing the parity gate
    # (matches the len(cases) > 0 guard in the classify_*_fixture_parity
    # tests above).
    assert len(fixture["steps"]) > 0, f"scenario fixture {fixture_name} has no steps"

    failures: list[str] = []

    for idx, step in enumerate(fixture["steps"]):
        kind = step["step"]["kind"]
        expected = step["after"]

        if kind == "observe":
            r = _round_from_fixture(step["step"]["round"])
            killed = step["step"]["round"].get("killed")
            ratio = step["step"].get("lowest_hp_ratio")
            cls = tracker.observe(r, killed, ratio)
            expected_cls = _classification_from_fixture(expected["classification"])
            if cls != expected_cls:
                failures.append(
                    f"step {idx}: classification expected {expected_cls!r}, got {cls!r}"
                )
        elif kind == "tick":
            tracker.tick()
        elif kind == "update_stakes":
            tracker.update_stakes(step["step"]["current_hp"], step["step"]["max_hp"])
        else:  # pragma: no cover - defensive
            raise ValueError(f"unknown step kind: {kind}")

        if not _approx(tracker.action_tension(), expected["action_tension"]):
            failures.append(
                f"step {idx}: action_tension expected {expected['action_tension']}, "
                f"got {tracker.action_tension()}"
            )
        if not _approx(tracker.stakes_tension(), expected["stakes_tension"]):
            failures.append(
                f"step {idx}: stakes_tension expected {expected['stakes_tension']}, "
                f"got {tracker.stakes_tension()}"
            )
        if not _approx(tracker.drama_weight(), expected["drama_weight"]):
            failures.append(
                f"step {idx}: drama_weight expected {expected['drama_weight']}, "
                f"got {tracker.drama_weight()}"
            )
        if not _approx(tracker.active_spike(), expected["active_spike"]):
            failures.append(
                f"step {idx}: active_spike expected {expected['active_spike']}, "
                f"got {tracker.active_spike()}"
            )
        if tracker.boring_streak() != expected["boring_streak"]:
            failures.append(
                f"step {idx}: boring_streak expected {expected['boring_streak']}, "
                f"got {tracker.boring_streak()}"
            )

        hint = tracker.pacing_hint(th)
        ph_expected = expected["pacing_hint"]
        if not _approx(hint.drama_weight, ph_expected["drama_weight"]):
            failures.append(
                f"step {idx}: pacing_hint.drama_weight expected "
                f"{ph_expected['drama_weight']}, got {hint.drama_weight}"
            )
        if hint.target_sentences != ph_expected["target_sentences"]:
            failures.append(
                f"step {idx}: pacing_hint.target_sentences expected "
                f"{ph_expected['target_sentences']}, got {hint.target_sentences}"
            )
        if hint.delivery_mode.name != ph_expected["delivery_mode"]:
            failures.append(
                f"step {idx}: pacing_hint.delivery_mode expected "
                f"{ph_expected['delivery_mode']}, got {hint.delivery_mode.name}"
            )
        if hint.escalation_beat != ph_expected["escalation_beat"]:
            failures.append(
                f"step {idx}: pacing_hint.escalation_beat expected "
                f"{ph_expected['escalation_beat']!r}, got {hint.escalation_beat!r}"
            )
        if hint.narrator_directive() != ph_expected["narrator_directive"]:
            failures.append(
                f"step {idx}: narrator_directive expected "
                f"{ph_expected['narrator_directive']!r}, got "
                f"{hint.narrator_directive()!r}"
            )

    assert not failures, f"scenario '{fixture_name}' parity drift:\n" + "\n".join(failures)


def test_scenario_escalating_parity():
    _replay_scenario("scenario_escalating.json")


def test_scenario_stalling_parity():
    _replay_scenario("scenario_stalling.json")


def test_scenario_reversal_parity():
    _replay_scenario("scenario_reversal.json")


# =========================================================================
# AC4 — DramaThresholds sourced from genre pack: thresholds drive shifts.
#        A pack with a lower streaming_delivery_min should flip a mid-drama
#        tracker into Streaming where defaults would yield Sentence.
# =========================================================================


def test_pacing_hint_threshold_shift_lowers_streaming_floor():
    tracker = TensionTracker.with_values(0.5, 0.0)

    defaults = DramaThresholds()  # streaming_delivery_min defaults to 0.70
    default_hint = tracker.pacing_hint(defaults)
    assert default_hint.delivery_mode == DeliveryMode.Sentence, (
        f"with default thresholds at drama 0.5, expected Sentence delivery, got {default_hint.delivery_mode.name}"
    )

    aggressive = DramaThresholds(streaming_delivery_min=0.40, sentence_delivery_min=0.20)
    custom_hint = tracker.pacing_hint(aggressive)
    assert custom_hint.delivery_mode == DeliveryMode.Streaming, (
        f"with aggressive thresholds at drama 0.5, expected Streaming, got {custom_hint.delivery_mode.name}"
    )


def test_pacing_hint_escalation_streak_threshold_shift():
    tracker = TensionTracker()
    for _ in range(3):
        tracker.record_event(CombatEvent.Boring)

    # Defaults: escalation_streak=5 → no beat at streak 3.
    defaults = DramaThresholds()
    assert tracker.boring_streak() == 3
    assert tracker.pacing_hint(defaults).escalation_beat is None

    # Lower the escalation threshold below current streak — beat should fire.
    relaxed = DramaThresholds(escalation_streak=2)
    beat = tracker.pacing_hint(relaxed).escalation_beat
    assert beat is not None and "environment shifts" in beat


# =========================================================================
# AC4 — TensionTracker reads thresholds from genre pack, not constants.
#       Pacing hint must accept a DramaThresholds and use its values.
# =========================================================================


def test_pacing_hint_signature_requires_thresholds():
    tracker = TensionTracker()
    # Calling without thresholds must be a TypeError — proves the contract.
    with pytest.raises(TypeError):
        tracker.pacing_hint()  # type: ignore[call-arg]


# =========================================================================
# AC5 — 1:1 Rust port assertion.
#       Sanity: count #[test] in tension_tracker.rs and assert this file
#       has at least that many ported tests with matching names.
# =========================================================================


RUST_SOURCE = (
    Path(__file__).parent.parent.parent.parent
    / "sidequest-api"
    / "crates"
    / "sidequest-game"
    / "src"
    / "tension_tracker.rs"
)


def _rust_test_names() -> list[str]:
    """Parse Rust ``#[test] fn <name>()`` declarations from the live source.

    Caller is responsible for skipping the test if ``RUST_SOURCE`` is
    absent — see the ``@pytest.mark.skipif`` decorator on the test.
    """
    text = RUST_SOURCE.read_text(encoding="utf-8")
    names: list[str] = []
    lines = text.splitlines()
    for i, line in enumerate(lines):
        if line.strip() == "#[test]":
            for j in range(i + 1, min(i + 6, len(lines))):
                stripped = lines[j].strip()
                if stripped.startswith("fn "):
                    name = stripped[3:].split("(", 1)[0].strip()
                    names.append(name)
                    break
    return names


@pytest.mark.skipif(
    not RUST_SOURCE.exists(),
    reason=(
        "1:1 Rust port parity check requires sidequest-api co-located at "
        "../sidequest-api. Skip is visible in the pytest report rather "
        "than buried inside a helper (CLAUDE.md no-silent-fallbacks)."
    ),
)
def test_every_rust_test_has_python_counterpart():
    rust_names = _rust_test_names()
    assert rust_names, "expected to find Rust test names"
    module_globals = globals()
    missing = [n for n in rust_names if f"test_{n}" not in module_globals]
    assert not missing, (
        "Rust tests not ported 1:1 to Python (need test_<name> for each):\n"
        + "\n".join(f"  - {n}" for n in missing)
    )
