"""GameStateView — narrow, read-only projection of session state the filter reads.

Implemented by SessionHandler (SessionGameStateView, added in Task 3).
Filter never mutates. Every method returns None where state is unknown
rather than raising — the filter treats unknown relationships conservatively.
"""
from __future__ import annotations

from typing import Protocol


class GameStateView(Protocol):
    def is_gm(self, player_id: str) -> bool: ...
    def seat_of(self, player_id: str) -> str | None: ...
    def character_of(self, player_id: str) -> str | None: ...
    def zone_of(self, character_id: str) -> str | None: ...
    def visible_to(self, viewer_character_id: str, target_character_id: str) -> bool: ...
    def owner_of_item(self, item_id: str) -> str | None: ...
    def party_of(self, player_id: str) -> str | None: ...
