"""sidequest.genre — genre pack loading, resolution, and models.

Public re-exports from foundation layer (Story 41-2).
Subagent C will add GenreLoader and the archetype shim.
"""

from sidequest.genre.cache import GenreCache
from sidequest.genre.error import (
    GenreCycleError,
    GenreError,
    GenreIoError,
    GenreLoadError,
    GenreMissingParentError,
    GenreNotFoundError,
    GenreValidationError,
    SchemaValidationError,
    ValidationErrors,
)
from sidequest.genre.genre_code import GenreCode
from sidequest.genre.models import (
    AdvancementEffect,
    AdvancementTier,
    AdvancementTree,
    ArchetypeConstraints,
    ArchetypeFunnels,
    ArchetypeResolved,
    AudioConfig,
    AxesConfig,
    BackstoryTables,
    BaseArchetypes,
    BeatDef,
    BeatVocabulary,
    CartographyConfig,
    CharCreationScene,
    ConfrontationDef,
    Culture,
    DramaThresholds,
    GenrePack,
    GenreTheme,
    InventoryConfig,
    Legend,
    Lore,
    MixerConfig,
    NpcArchetype,
    NpcTraitsDatabase,
    OceanProfile,
    OpeningHook,
    PackMeta,
    Prompts,
    ProgressionConfig,
    RecoveryTrigger,
    RulesConfig,
    ScenarioPack,
    TropeDefinition,
    VisualStyle,
    World,
    WorldConfig,
    WorldLore,
)
from sidequest.genre.resolver import (
    LayeredMerge,
    MergeStrategy,
    ResolutionContext,
    Resolved,
    Resolver,
)

__all__ = [
    # genre_code
    "GenreCode",
    # resolver
    "LayeredMerge",
    "MergeStrategy",
    "ResolutionContext",
    "Resolved",
    "Resolver",
    # errors
    "GenreError",
    "GenreLoadError",
    "GenreCycleError",
    "GenreMissingParentError",
    "GenreValidationError",
    "GenreIoError",
    "GenreNotFoundError",
    "SchemaValidationError",
    "ValidationErrors",
    # cache
    "GenreCache",
    # models — key public types
    "AdvancementEffect",
    "AdvancementTier",
    "AdvancementTree",
    "ArchetypeConstraints",
    "ArchetypeFunnels",
    "ArchetypeResolved",
    "AudioConfig",
    "AxesConfig",
    "BackstoryTables",
    "BaseArchetypes",
    "BeatDef",
    "BeatVocabulary",
    "CartographyConfig",
    "CharCreationScene",
    "ConfrontationDef",
    "Culture",
    "DramaThresholds",
    "GenrePack",
    "GenreTheme",
    "InventoryConfig",
    "Legend",
    "Lore",
    "MixerConfig",
    "NpcArchetype",
    "NpcTraitsDatabase",
    "OceanProfile",
    "OpeningHook",
    "PackMeta",
    "Prompts",
    "ProgressionConfig",
    "RecoveryTrigger",
    "RulesConfig",
    "ScenarioPack",
    "TropeDefinition",
    "VisualStyle",
    "World",
    "WorldConfig",
    "WorldLore",
]
